(function(){
  function clamp(value, min, max) {
    return Math.min(Math.max(value, min), max);
  }

  function slugify(text) {
    return (text || '')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      || 'player';
  }

  const ROLE_TWEAKS = {
    GK:   { pace: -35, shooting: -48, passing: -10, dribbling: -12, defending: -52, physical: -8 },
    CB:   { pace: -8, shooting: -25, passing: -6, dribbling: -10, defending: 6, physical: 4 },
    LB:   { pace: 6, shooting: -10, passing: 2, dribbling: 3, defending: -2, physical: 0 },
    RB:   { pace: 6, shooting: -10, passing: 2, dribbling: 3, defending: -2, physical: 0 },
    LWB:  { pace: 7, shooting: -8, passing: 3, dribbling: 4, defending: -3, physical: -1 },
    RWB:  { pace: 7, shooting: -8, passing: 3, dribbling: 4, defending: -3, physical: -1 },
    CDM:  { pace: -4, shooting: -8, passing: 4, dribbling: -2, defending: 6, physical: 4 },
    CM:   { pace: 0, shooting: -4, passing: 5, dribbling: 2, defending: 0, physical: 0 },
    AM:   { pace: 2, shooting: 2, passing: 4, dribbling: 6, defending: -6, physical: -2 },
    RW:   { pace: 8, shooting: 3, passing: 2, dribbling: 8, defending: -8, physical: -2 },
    LW:   { pace: 8, shooting: 3, passing: 2, dribbling: 8, defending: -8, physical: -2 },
    ST:   { pace: 4, shooting: 8, passing: -3, dribbling: 0, defending: -8, physical: 4 },
  };

  function variance(key, seed) {
    let hash = 0;
    const source = `${seed}-${key}`;
    for (let i = 0; i < source.length; i += 1) {
      hash = (hash * 31 + source.charCodeAt(i)) % 97;
    }
    return (hash % 7) - 3; // -3 .. +3
  }

  function buildAttributes(pos, rating, id) {
    const tweak = ROLE_TWEAKS[pos] || { pace: 0, shooting: 0, passing: 0, dribbling: 0, defending: 0, physical: 0 };
    const attrs = {
      pace: clamp(Math.round(rating + tweak.pace + variance('pace', id)), 25, 95),
      shooting: clamp(Math.round(rating + tweak.shooting + variance('shooting', id)), 25, 95),
      passing: clamp(Math.round(rating + tweak.passing + variance('passing', id)), 30, 95),
      dribbling: clamp(Math.round(rating + tweak.dribbling + variance('dribbling', id)), 30, 95),
      defending: clamp(Math.round(rating + tweak.defending + variance('defending', id)), 25, 95),
      physical: clamp(Math.round(rating + tweak.physical + variance('physical', id)), 30, 95),
    };
    attrs.overall = rating;
    return attrs;
  }

  const baseTeams = [
    {
      code: 'psg',
      name: 'Paris Saint-Germain',
      shortName: 'PSG',
      balance: 920000,
      ticketsPrice: 36,
      sponsor: { name: 'Qatar Airways', monthly: 205000 },
      players: [
        { name: 'Gianluigi Donnarumma', pos: 'GK', age: 26, rating: 89 },
        { name: 'Arnau Tenas', pos: 'GK', age: 24, rating: 76 },
        { name: 'Achraf Hakimi', pos: 'RB', age: 27, rating: 87 },
        { name: 'Marquinhos', pos: 'CB', age: 31, rating: 87 },
        { name: 'Lucas Beraldo', pos: 'CB', age: 22, rating: 82 },
        { name: 'Leny Yoro', pos: 'CB', age: 20, rating: 85 },
        { name: 'Nuno Mendes', pos: 'LB', age: 23, rating: 85 },
        { name: 'Manuel Ugarte', pos: 'CDM', age: 24, rating: 83 },
        { name: 'Vitinha', pos: 'CM', age: 25, rating: 84 },
        { name: 'Warren Zaïre-Emery', pos: 'CM', age: 21, rating: 85 },
        { name: 'Xavi Simons', pos: 'AM', age: 22, rating: 86 },
        { name: 'Ousmane Dembélé', pos: 'RW', age: 28, rating: 87 },
        { name: 'Bradley Barcola', pos: 'LW', age: 23, rating: 83 },
        { name: 'Kang-in Lee', pos: 'AM', age: 24, rating: 83 },
        { name: 'Randal Kolo Muani', pos: 'ST', age: 27, rating: 85 },
        { name: 'Gonçalo Ramos', pos: 'ST', age: 24, rating: 84 },
        { name: 'Victor Osimhen', pos: 'ST', age: 26, rating: 89 },
        { name: 'João Neves', pos: 'CM', age: 21, rating: 85 },
      ],
    },
    {
      code: 'asm',
      name: 'AS Monaco',
      shortName: 'Monaco',
      balance: 510000,
      ticketsPrice: 28,
      sponsor: { name: 'Fedcom', monthly: 125000 },
      players: [
        { name: 'Philipp Köhn', pos: 'GK', age: 27, rating: 81 },
        { name: 'Radoslaw Majecki', pos: 'GK', age: 26, rating: 75 },
        { name: 'Vanderson', pos: 'RB', age: 24, rating: 82 },
        { name: 'Wilfried Singo', pos: 'CB', age: 25, rating: 82 },
        { name: 'Thilo Kehrer', pos: 'CB', age: 29, rating: 81 },
        { name: 'Ismail Jakobs', pos: 'LB', age: 26, rating: 80 },
        { name: 'Guillermo Maripán', pos: 'CB', age: 31, rating: 80 },
        { name: 'Denis Zakaria', pos: 'CDM', age: 28, rating: 83 },
        { name: 'Youssouf Fofana', pos: 'CM', age: 26, rating: 85 },
        { name: 'Mohamed Camara', pos: 'CM', age: 25, rating: 82 },
        { name: 'Aleksandr Golovin', pos: 'AM', age: 29, rating: 84 },
        { name: 'Takumi Minamino', pos: 'AM', age: 30, rating: 81 },
        { name: 'Eliesse Ben Seghir', pos: 'AM', age: 20, rating: 80 },
        { name: 'Breel Embolo', pos: 'ST', age: 28, rating: 83 },
        { name: 'Folarin Balogun', pos: 'ST', age: 24, rating: 84 },
        { name: 'Wissam Ben Yedder', pos: 'ST', age: 35, rating: 83 },
        { name: 'Krépin Diatta', pos: 'RW', age: 26, rating: 82 },
        { name: 'Maghnes Akliouche', pos: 'AM', age: 23, rating: 80 },
      ],
    },
    {
      code: 'mar',
      name: 'Olympique de Marseille',
      shortName: 'Marseille',
      balance: 470000,
      ticketsPrice: 26,
      sponsor: { name: 'CMA CGM', monthly: 118000 },
      players: [
        { name: 'Pau López', pos: 'GK', age: 30, rating: 82 },
        { name: 'Rubén Blanco', pos: 'GK', age: 29, rating: 75 },
        { name: 'Jonathan Clauss', pos: 'RB', age: 33, rating: 84 },
        { name: 'Chancel Mbemba', pos: 'CB', age: 31, rating: 83 },
        { name: 'Leonardo Balerdi', pos: 'CB', age: 26, rating: 81 },
        { name: 'Bamo Meïté', pos: 'CB', age: 23, rating: 78 },
        { name: 'Quentin Merlin', pos: 'LB', age: 23, rating: 80 },
        { name: 'Samuel Gigot', pos: 'CB', age: 31, rating: 81 },
        { name: 'Geoffrey Kondogbia', pos: 'CDM', age: 32, rating: 82 },
        { name: 'Jordan Veretout', pos: 'CM', age: 32, rating: 82 },
        { name: 'Azzedine Ounahi', pos: 'CM', age: 25, rating: 82 },
        { name: 'Amine Harit', pos: 'AM', age: 28, rating: 81 },
        { name: 'Ismaïla Sarr', pos: 'RW', age: 27, rating: 83 },
        { name: 'Iliman Ndiaye', pos: 'ST', age: 26, rating: 81 },
        { name: 'Pierre-Emerick Aubameyang', pos: 'ST', age: 36, rating: 82 },
        { name: 'Luis Henrique', pos: 'LW', age: 24, rating: 80 },
        { name: 'Faris Moumbagna', pos: 'ST', age: 25, rating: 79 },
        { name: 'Michael Murillo', pos: 'RB', age: 29, rating: 79 },
      ],
    },
    {
      code: 'ol',
      name: 'Olympique Lyonnais',
      shortName: 'Lyon',
      balance: 430000,
      ticketsPrice: 25,
      sponsor: { name: 'Emirates', monthly: 110000 },
      players: [
        { name: 'Anthony Lopes', pos: 'GK', age: 34, rating: 82 },
        { name: 'Lucas Perri', pos: 'GK', age: 27, rating: 78 },
        { name: 'Jake O’Brien', pos: 'CB', age: 24, rating: 80 },
        { name: 'Sinaly Diomandé', pos: 'CB', age: 24, rating: 80 },
        { name: 'Clinton Mata', pos: 'RB', age: 32, rating: 80 },
        { name: 'Nicolás Tagliafico', pos: 'LB', age: 33, rating: 83 },
        { name: 'Maxence Caqueret', pos: 'CM', age: 25, rating: 84 },
        { name: 'Corentin Tolisso', pos: 'CM', age: 31, rating: 82 },
        { name: 'Johann Lepenant', pos: 'CDM', age: 23, rating: 79 },
        { name: 'Rayan Cherki', pos: 'AM', age: 22, rating: 83 },
        { name: 'Ernest Nuamah', pos: 'RW', age: 22, rating: 82 },
        { name: 'Alexandre Lacazette', pos: 'ST', age: 34, rating: 84 },
        { name: 'Gift Orban', pos: 'ST', age: 23, rating: 82 },
        { name: 'Saïd Benrahma', pos: 'LW', age: 29, rating: 81 },
        { name: 'Malick Fofana', pos: 'RW', age: 21, rating: 79 },
        { name: 'Diego Moreira', pos: 'LW', age: 20, rating: 77 },
        { name: 'Amin Sarr', pos: 'ST', age: 24, rating: 78 },
      ],
    },
    {
      code: 'losc',
      name: 'Lille OSC',
      shortName: 'Lille',
      balance: 400000,
      ticketsPrice: 24,
      sponsor: { name: 'Boulanger', monthly: 100000 },
      players: [
        { name: 'Lucas Chevalier', pos: 'GK', age: 24, rating: 83 },
        { name: 'Adam Jakubech', pos: 'GK', age: 27, rating: 74 },
        { name: 'Leny Yoro', pos: 'CB', age: 20, rating: 86 },
        { name: 'Alexsandro Ribeiro', pos: 'CB', age: 26, rating: 80 },
        { name: 'Bafodé Diakité', pos: 'CB', age: 24, rating: 82 },
        { name: 'Ismaily', pos: 'LB', age: 35, rating: 79 },
        { name: 'Tiago Santos', pos: 'RB', age: 22, rating: 81 },
        { name: 'Benjamin André', pos: 'CDM', age: 35, rating: 82 },
        { name: 'Angel Gomes', pos: 'CM', age: 25, rating: 83 },
        { name: 'Nabil Bentaleb', pos: 'CM', age: 31, rating: 82 },
        { name: 'Edon Zhegrova', pos: 'RW', age: 26, rating: 83 },
        { name: 'Hákon Haraldsson', pos: 'AM', age: 22, rating: 80 },
        { name: 'Jonathan David', pos: 'ST', age: 25, rating: 86 },
        { name: 'Yusuf Yazıcı', pos: 'AM', age: 28, rating: 81 },
        { name: 'Mohamed Bayo', pos: 'ST', age: 27, rating: 80 },
        { name: 'Rémy Cabella', pos: 'AM', age: 35, rating: 80 },
        { name: 'Alan Virginius', pos: 'RW', age: 22, rating: 78 },
      ],
    },
    {
      code: 'srfc',
      name: 'Stade Rennais',
      shortName: 'Rennes',
      balance: 380000,
      ticketsPrice: 23,
      sponsor: { name: 'Samsic', monthly: 98000 },
      players: [
        { name: 'Steve Mandanda', pos: 'GK', age: 40, rating: 80 },
        { name: 'Doğan Alemdar', pos: 'GK', age: 23, rating: 76 },
        { name: 'Warmed Omari', pos: 'CB', age: 25, rating: 80 },
        { name: 'Arthur Theate', pos: 'CB', age: 25, rating: 83 },
        { name: 'Christopher Wooh', pos: 'CB', age: 24, rating: 80 },
        { name: 'Adrien Truffert', pos: 'LB', age: 23, rating: 82 },
        { name: 'Lorenz Assignon', pos: 'RB', age: 24, rating: 79 },
        { name: 'Benjamin Bourigeaud', pos: 'CM', age: 31, rating: 84 },
        { name: 'Baptiste Santamaria', pos: 'CDM', age: 30, rating: 81 },
        { name: 'Enzo Le Fée', pos: 'CM', age: 25, rating: 84 },
        { name: 'Désiré Doué', pos: 'AM', age: 20, rating: 82 },
        { name: 'Ludovic Blas', pos: 'AM', age: 27, rating: 82 },
        { name: 'Martin Terrier', pos: 'ST', age: 28, rating: 84 },
        { name: 'Amine Gouiri', pos: 'ST', age: 25, rating: 83 },
        { name: 'Arnaud Kalimuendo', pos: 'ST', age: 23, rating: 82 },
        { name: 'Ibrahim Salah', pos: 'LW', age: 23, rating: 78 },
        { name: 'Fabian Rieder', pos: 'CM', age: 23, rating: 80 },
      ],
    },
    {
      code: 'ogcn',
      name: 'OGC Nice',
      shortName: 'Nice',
      balance: 360000,
      ticketsPrice: 23,
      sponsor: { name: 'INEOS', monthly: 94000 },
      players: [
        { name: 'Marcin Bułka', pos: 'GK', age: 26, rating: 82 },
        { name: 'Teddy Boulhendi', pos: 'GK', age: 24, rating: 73 },
        { name: 'Jean-Clair Todibo', pos: 'CB', age: 25, rating: 85 },
        { name: 'Dante', pos: 'CB', age: 41, rating: 79 },
        { name: 'Youssouf Ndayishimiye', pos: 'CB', age: 26, rating: 82 },
        { name: 'Jordan Lotomba', pos: 'RB', age: 26, rating: 80 },
        { name: 'Melvin Bard', pos: 'LB', age: 24, rating: 81 },
        { name: 'Khéphren Thuram', pos: 'CM', age: 25, rating: 84 },
        { name: 'Pablo Rosario', pos: 'CDM', age: 28, rating: 81 },
        { name: 'Morgan Sanson', pos: 'CM', age: 31, rating: 80 },
        { name: 'Sofiane Diop', pos: 'AM', age: 24, rating: 82 },
        { name: 'Jérémie Boga', pos: 'LW', age: 28, rating: 82 },
        { name: 'Terem Moffi', pos: 'ST', age: 26, rating: 84 },
        { name: 'Gaëtan Laborde', pos: 'ST', age: 31, rating: 82 },
        { name: 'Evann Guessand', pos: 'ST', age: 24, rating: 79 },
        { name: 'Alexis Claude-Maurice', pos: 'AM', age: 27, rating: 79 },
        { name: 'Badredine Bouanani', pos: 'RW', age: 21, rating: 78 },
      ],
    },
    {
      code: 'rcl',
      name: 'RC Lens',
      shortName: 'Lens',
      balance: 330000,
      ticketsPrice: 22,
      sponsor: { name: 'Auchan', monthly: 88000 },
      players: [
        { name: 'Brice Samba', pos: 'GK', age: 31, rating: 84 },
        { name: 'Jean-Louis Leca', pos: 'GK', age: 40, rating: 75 },
        { name: 'Kevin Danso', pos: 'CB', age: 27, rating: 84 },
        { name: 'Facundo Medina', pos: 'CB', age: 26, rating: 83 },
        { name: 'Jonathan Gradit', pos: 'CB', age: 32, rating: 82 },
        { name: 'Przemysław Frankowski', pos: 'RWB', age: 30, rating: 82 },
        { name: 'Deiver Machado', pos: 'LWB', age: 32, rating: 81 },
        { name: 'Salis Abdul Samed', pos: 'CDM', age: 25, rating: 82 },
        { name: 'Andy Diouf', pos: 'CM', age: 23, rating: 80 },
        { name: 'Angelo Fulgini', pos: 'AM', age: 29, rating: 81 },
        { name: 'Adrien Thomasson', pos: 'AM', age: 31, rating: 81 },
        { name: 'Elye Wahi', pos: 'ST', age: 22, rating: 83 },
        { name: 'Florian Sotoca', pos: 'ST', age: 34, rating: 82 },
        { name: 'Morgan Guilavogui', pos: 'ST', age: 27, rating: 80 },
        { name: 'David Pereira da Costa', pos: 'AM', age: 24, rating: 81 },
        { name: 'Neil El Aynaoui', pos: 'CM', age: 24, rating: 78 },
        { name: 'Jimmy Cabot', pos: 'RW', age: 31, rating: 78 },
      ],
    },
    {
      code: 'sb29',
      name: 'Stade Brestois 29',
      shortName: 'Brest',
      balance: 260000,
      ticketsPrice: 20,
      sponsor: { name: 'Queguiner', monthly: 64000 },
      players: [
        { name: 'Marco Bizot', pos: 'GK', age: 34, rating: 81 },
        { name: 'Joaquín Blázquez', pos: 'GK', age: 24, rating: 74 },
        { name: 'Lilian Brassier', pos: 'CB', age: 25, rating: 81 },
        { name: 'Brendan Chardonnet', pos: 'CB', age: 31, rating: 80 },
        { name: 'Kenny Lala', pos: 'RB', age: 34, rating: 79 },
        { name: 'Bradley Locko', pos: 'LB', age: 24, rating: 80 },
        { name: 'Pierre Lees-Melou', pos: 'CM', age: 32, rating: 82 },
        { name: 'Hugo Magnetti', pos: 'CM', age: 27, rating: 78 },
        { name: 'Mahdi Camara', pos: 'CM', age: 27, rating: 80 },
        { name: 'Romain Del Castillo', pos: 'RW', age: 29, rating: 82 },
        { name: 'Kamory Doumbia', pos: 'AM', age: 23, rating: 80 },
        { name: 'Jérémy Le Douaron', pos: 'LW', age: 27, rating: 80 },
        { name: 'Steve Mounié', pos: 'ST', age: 31, rating: 81 },
        { name: 'Martin Satriano', pos: 'ST', age: 24, rating: 79 },
        { name: 'Mathias Pereira Lage', pos: 'AM', age: 29, rating: 78 },
        { name: 'Jonas Martin', pos: 'CM', age: 35, rating: 77 },
      ],
    },
    {
      code: 'tfc',
      name: 'Toulouse FC',
      shortName: 'Toulouse',
      balance: 250000,
      ticketsPrice: 19,
      sponsor: { name: 'Newrest', monthly: 60000 },
      players: [
        { name: 'Guillaume Restes', pos: 'GK', age: 20, rating: 82 },
        { name: 'Álex Domínguez', pos: 'GK', age: 29, rating: 75 },
        { name: 'Logan Costa', pos: 'CB', age: 24, rating: 80 },
        { name: 'Rasmus Nicolaisen', pos: 'CB', age: 28, rating: 80 },
        { name: 'Moussa Diarra', pos: 'LB', age: 24, rating: 79 },
        { name: 'Gabriel Suazo', pos: 'LB', age: 27, rating: 80 },
        { name: 'Mikkel Desler', pos: 'RB', age: 30, rating: 80 },
        { name: 'Vincent Sierro', pos: 'CM', age: 30, rating: 81 },
        { name: 'Stijn Spierings', pos: 'CM', age: 29, rating: 80 },
        { name: 'Cristian Cásseres Jr.', pos: 'CM', age: 27, rating: 80 },
        { name: 'Zakaria Aboukhlal', pos: 'RW', age: 25, rating: 83 },
        { name: 'Yann Gboho', pos: 'LW', age: 24, rating: 78 },
        { name: 'Thijs Dallinga', pos: 'ST', age: 25, rating: 84 },
        { name: 'Frank Magri', pos: 'ST', age: 26, rating: 79 },
        { name: 'Ibrahim Cissoko', pos: 'RW', age: 22, rating: 77 },
        { name: 'Niklas Schmidt', pos: 'CM', age: 27, rating: 79 },
      ],
    },
    {
      code: 'sdr',
      name: 'Stade de Reims',
      shortName: 'Reims',
      balance: 280000,
      ticketsPrice: 20,
      sponsor: { name: 'Hexaôm', monthly: 72000 },
      players: [
        { name: 'Yehvann Diouf', pos: 'GK', age: 25, rating: 82 },
        { name: 'Patrick Pentz', pos: 'GK', age: 29, rating: 78 },
        { name: 'Yunis Abdelhamid', pos: 'CB', age: 38, rating: 79 },
        { name: 'Emmanuel Agbadou', pos: 'CB', age: 28, rating: 80 },
        { name: 'Thibault De Smet', pos: 'LB', age: 25, rating: 79 },
        { name: 'Thomas Foket', pos: 'RB', age: 30, rating: 81 },
        { name: 'Marshall Munetsi', pos: 'CDM', age: 29, rating: 83 },
        { name: 'Azor Matusiwa', pos: 'CDM', age: 27, rating: 82 },
        { name: 'Teddy Teuma', pos: 'CM', age: 31, rating: 82 },
        { name: 'Amir Richardson', pos: 'CM', age: 23, rating: 80 },
        { name: 'Junya Ito', pos: 'RW', age: 32, rating: 84 },
        { name: 'Mohamed Daramy', pos: 'LW', age: 23, rating: 82 },
        { name: 'Oumar Diakité', pos: 'ST', age: 22, rating: 80 },
        { name: 'Amine Salama', pos: 'ST', age: 24, rating: 79 },
        { name: 'Jovane Cabral', pos: 'LW', age: 27, rating: 78 },
        { name: 'Keito Nakamura', pos: 'LW', age: 25, rating: 81 },
      ],
    },
    {
      code: 'rcsa',
      name: 'RC Strasbourg Alsace',
      shortName: 'Strasbourg',
      balance: 240000,
      ticketsPrice: 19,
      sponsor: { name: 'Hager', monthly: 64000 },
      players: [
        { name: 'Matz Sels', pos: 'GK', age: 33, rating: 82 },
        { name: 'Alaa Bellaarouch', pos: 'GK', age: 23, rating: 74 },
        { name: 'Gerzino Nyamsi', pos: 'CB', age: 28, rating: 80 },
        { name: 'Ismaël Doukouré', pos: 'CB', age: 22, rating: 80 },
        { name: 'Lucas Perrin', pos: 'CB', age: 27, rating: 79 },
        { name: 'Frédéric Guilbert', pos: 'RB', age: 30, rating: 81 },
        { name: 'Thomas Delaine', pos: 'LB', age: 33, rating: 79 },
        { name: 'Ibrahima Sissoko', pos: 'CM', age: 28, rating: 80 },
        { name: 'Sanjin Prcić', pos: 'CM', age: 31, rating: 80 },
        { name: 'Habib Diarra', pos: 'CM', age: 22, rating: 82 },
        { name: 'Dilane Bakwa', pos: 'RW', age: 22, rating: 79 },
        { name: 'Angelo Gabriel', pos: 'RW', age: 20, rating: 81 },
        { name: 'Emanuel Emegha', pos: 'ST', age: 24, rating: 80 },
        { name: 'Lebo Mothiba', pos: 'ST', age: 29, rating: 79 },
        { name: 'Kévin Gameiro', pos: 'ST', age: 38, rating: 78 },
        { name: 'Moïse Sahi Dion', pos: 'ST', age: 23, rating: 78 },
        { name: 'Marvin Senaya', pos: 'RB', age: 23, rating: 78 },
      ],
    },
    {
      code: 'mhsc',
      name: 'Montpellier HSC',
      shortName: 'Montpellier',
      balance: 230000,
      ticketsPrice: 19,
      sponsor: { name: 'Sud de France', monthly: 60000 },
      players: [
        { name: 'Benjamin Lecomte', pos: 'GK', age: 34, rating: 81 },
        { name: 'Dimitry Bertaud', pos: 'GK', age: 27, rating: 75 },
        { name: 'Christopher Jullien', pos: 'CB', age: 32, rating: 79 },
        { name: 'Maxime Estève', pos: 'CB', age: 23, rating: 80 },
        { name: 'Falaye Sacko', pos: 'RB', age: 30, rating: 79 },
        { name: 'Issiaga Sylla', pos: 'LB', age: 32, rating: 78 },
        { name: 'Jordan Ferri', pos: 'CM', age: 33, rating: 80 },
        { name: 'Joris Chotard', pos: 'CM', age: 23, rating: 81 },
        { name: 'Téji Savanier', pos: 'AM', age: 33, rating: 85 },
        { name: 'Arnaud Nordin', pos: 'RW', age: 27, rating: 82 },
        { name: 'Musa Al-Taamari', pos: 'LW', age: 28, rating: 82 },
        { name: 'Akor Adams', pos: 'ST', age: 25, rating: 83 },
        { name: 'Wahbi Khazri', pos: 'ST', age: 34, rating: 79 },
        { name: 'Khalil Fayad', pos: 'CM', age: 21, rating: 78 },
        { name: 'Léo Leroy', pos: 'CM', age: 25, rating: 78 },
        { name: 'Serigne Faye', pos: 'ST', age: 22, rating: 77 },
      ],
    },
    {
      code: 'fcn',
      name: 'FC Nantes',
      shortName: 'Nantes',
      balance: 240000,
      ticketsPrice: 19,
      sponsor: { name: 'Synergie', monthly: 65000 },
      players: [
        { name: 'Alban Lafont', pos: 'GK', age: 26, rating: 83 },
        { name: 'Rémy Descamps', pos: 'GK', age: 29, rating: 74 },
        { name: 'Jean-Charles Castelletto', pos: 'CB', age: 30, rating: 80 },
        { name: 'Nicolas Pallois', pos: 'CB', age: 38, rating: 77 },
        { name: 'Fabien Centonze', pos: 'RB', age: 29, rating: 79 },
        { name: 'Jaouen Hadjam', pos: 'LB', age: 23, rating: 77 },
        { name: 'Douglas Augusto', pos: 'CM', age: 28, rating: 80 },
        { name: 'Pedro Chirivella', pos: 'CM', age: 28, rating: 81 },
        { name: 'Samuel Moutoussamy', pos: 'CM', age: 28, rating: 79 },
        { name: 'Florent Mollet', pos: 'AM', age: 34, rating: 80 },
        { name: 'Moses Simon', pos: 'LW', age: 30, rating: 82 },
        { name: 'Mostafa Mohamed', pos: 'ST', age: 28, rating: 83 },
        { name: 'Matthis Abline', pos: 'ST', age: 22, rating: 79 },
        { name: 'Marcus Coco', pos: 'RW', age: 29, rating: 78 },
        { name: 'Adson', pos: 'RW', age: 24, rating: 80 },
        { name: 'Ignatius Ganago', pos: 'ST', age: 26, rating: 80 },
      ],
    },
    {
      code: 'fcl',
      name: 'FC Lorient',
      shortName: 'Lorient',
      balance: 210000,
      ticketsPrice: 18,
      sponsor: { name: 'Actual', monthly: 54000 },
      players: [
        { name: 'Yvon Mvogo', pos: 'GK', age: 31, rating: 81 },
        { name: 'Vito Mannone', pos: 'GK', age: 37, rating: 76 },
        { name: 'Montassar Talbi', pos: 'CB', age: 25, rating: 82 },
        { name: 'Formose Mendy', pos: 'CB', age: 24, rating: 79 },
        { name: 'Julien Laporte', pos: 'CB', age: 31, rating: 79 },
        { name: 'Gédéon Kalulu', pos: 'RB', age: 28, rating: 79 },
        { name: 'Vincent Le Goff', pos: 'LB', age: 36, rating: 78 },
        { name: 'Laurent Abergel', pos: 'CDM', age: 32, rating: 81 },
        { name: 'Bonke Innocent', pos: 'CDM', age: 29, rating: 78 },
        { name: 'Jean-Victor Makengo', pos: 'CM', age: 27, rating: 80 },
        { name: 'Romain Faivre', pos: 'LW', age: 27, rating: 82 },
        { name: 'Théo Le Bris', pos: 'RW', age: 23, rating: 79 },
        { name: 'Bamba Dieng', pos: 'ST', age: 25, rating: 81 },
        { name: 'Eli Junior Kroupi', pos: 'ST', age: 19, rating: 80 },
        { name: 'Siriné Doucouré', pos: 'ST', age: 23, rating: 78 },
        { name: 'Julien Ponceau', pos: 'CM', age: 25, rating: 79 },
      ],
    },
    {
      code: 'fcmetz',
      name: 'FC Metz',
      shortName: 'Metz',
      balance: 200000,
      ticketsPrice: 17,
      sponsor: { name: 'Moselle Fibre', monthly: 52000 },
      players: [
        { name: 'Alexandre Oukidja', pos: 'GK', age: 37, rating: 80 },
        { name: 'Guillaume Dietsch', pos: 'GK', age: 24, rating: 74 },
        { name: 'Fali Candé', pos: 'CB', age: 27, rating: 79 },
        { name: 'Ismaël Traoré', pos: 'CB', age: 39, rating: 77 },
        { name: 'Matthieu Udol', pos: 'LB', age: 29, rating: 80 },
        { name: 'Kévin Van Den Kerkhof', pos: 'RB', age: 29, rating: 80 },
        { name: 'Habib Maïga', pos: 'CDM', age: 29, rating: 81 },
        { name: 'Kévin N’Doram', pos: 'CDM', age: 29, rating: 79 },
        { name: 'Lamine Camara', pos: 'CM', age: 22, rating: 80 },
        { name: 'Arthur Atta', pos: 'CM', age: 21, rating: 77 },
        { name: 'Georges Mikautadze', pos: 'ST', age: 25, rating: 84 },
        { name: 'Ablie Jallow', pos: 'RW', age: 27, rating: 79 },
        { name: 'Cheikh Sabaly', pos: 'RW', age: 25, rating: 78 },
        { name: 'Pape Diallo', pos: 'ST', age: 21, rating: 78 },
        { name: 'Papa Ndiaga Yade', pos: 'LW', age: 25, rating: 78 },
        { name: 'Lenny Joseph', pos: 'ST', age: 24, rating: 77 },
      ],
    },
    {
      code: 'asse',
      name: 'AS Saint-Étienne',
      shortName: 'Saint-Étienne',
      balance: 210000,
      ticketsPrice: 18,
      sponsor: { name: 'AEK Systems', monthly: 58000 },
      players: [
        { name: 'Gautier Larsonneur', pos: 'GK', age: 28, rating: 82 },
        { name: 'Étienne Green', pos: 'GK', age: 24, rating: 78 },
        { name: 'Anthony Briançon', pos: 'CB', age: 30, rating: 80 },
        { name: 'Mickaël Nadé', pos: 'CB', age: 26, rating: 79 },
        { name: 'Yvann Maçon', pos: 'RB', age: 26, rating: 78 },
        { name: 'Léo Pétrot', pos: 'LB', age: 28, rating: 78 },
        { name: 'Jimmy Giraudon', pos: 'CB', age: 33, rating: 77 },
        { name: 'Dylan Chambost', pos: 'CM', age: 28, rating: 80 },
        { name: 'Aimen Moueffek', pos: 'CM', age: 24, rating: 79 },
        { name: 'Victor Lobry', pos: 'CM', age: 29, rating: 78 },
        { name: 'Mathieu Cafaro', pos: 'RW', age: 29, rating: 80 },
        { name: 'Benjamin Bouchouari', pos: 'CM', age: 23, rating: 79 },
        { name: 'Irvin Cardona', pos: 'ST', age: 28, rating: 80 },
        { name: 'Jean-Philippe Krasso', pos: 'ST', age: 28, rating: 82 },
        { name: 'Ibrahima Wadji', pos: 'ST', age: 30, rating: 80 },
        { name: 'Niels Nkounkou', pos: 'LB', age: 25, rating: 80 },
        { name: 'Gaëtan Charbonnier', pos: 'ST', age: 36, rating: 78 },
      ],
    },
    {
      code: 'sco',
      name: 'Angers SCO',
      shortName: 'Angers',
      balance: 190000,
      ticketsPrice: 17,
      sponsor: { name: 'Scania', monthly: 50000 },
      players: [
        { name: 'Paul Bernardoni', pos: 'GK', age: 28, rating: 81 },
        { name: 'Yahia Fofana', pos: 'GK', age: 24, rating: 76 },
        { name: 'Cédric Hountondji', pos: 'CB', age: 31, rating: 78 },
        { name: 'Miha Blažič', pos: 'CB', age: 32, rating: 78 },
        { name: 'Yan Valery', pos: 'RB', age: 26, rating: 79 },
        { name: 'Souleyman Doumbia', pos: 'LB', age: 29, rating: 78 },
        { name: 'Batista Mendy', pos: 'CDM', age: 24, rating: 79 },
        { name: 'Pierrick Capelle', pos: 'CM', age: 38, rating: 76 },
        { name: 'Himad Abdelli', pos: 'AM', age: 25, rating: 80 },
        { name: 'Jean-Mattéo Bahoya', pos: 'AM', age: 20, rating: 79 },
        { name: 'Farid El Melali', pos: 'LW', age: 28, rating: 78 },
        { name: 'Casimir Ninga', pos: 'LW', age: 31, rating: 78 },
        { name: 'Adrien Hunou', pos: 'ST', age: 32, rating: 78 },
        { name: 'Loïs Diony', pos: 'ST', age: 32, rating: 78 },
        { name: 'Sada Thioub', pos: 'RW', age: 30, rating: 78 },
        { name: 'Halid Šabanović', pos: 'RB', age: 25, rating: 77 },
        { name: 'Zinedine Ould Khaled', pos: 'CM', age: 25, rating: 78 },
      ],
    },
  ];

  window.LIGUE1_DATA = {
    version: 'ligue1-2025-26-r1',
    teams: baseTeams.map((team) => {
      const players = team.players.map((player, index) => {
        const slug = slugify(player.name);
        const id = player.id || `${team.code}-${slug || `p${index}`}`;
        const rating = clamp(Math.round(player.rating), 45, 95);
        const attributes = buildAttributes(player.pos, rating, id);
        return {
          id,
          name: player.name,
          pos: player.pos,
          age: player.age,
          rating,
          attributes,
        };
      });
      return { ...team, players };
    }),
  };
})();
