window.LIGUE1_DATA = {
  version: 'ligue1-2023-24-r1',
  teams: [
    {
      code: 'psg',
      name: 'Paris Saint-Germain',
      shortName: 'PSG',
      balance: 850000,
      ticketsPrice: 32,
      sponsor: { name: 'Qatar Airways', monthly: 180000 },
      players: [
        { name: 'Gianluigi Donnarumma', pos: 'GK', age: 24, rating: 88, attributes: { pace: 52, shooting: 29, passing: 65, dribbling: 53, defending: 18, physical: 80, overall: 88 } },
        { name: 'Keylor Navas', pos: 'GK', age: 36, rating: 85, attributes: { pace: 50, shooting: 23, passing: 70, dribbling: 55, defending: 20, physical: 70, overall: 85 } },
        { name: 'Achraf Hakimi', pos: 'RB', age: 24, rating: 85, attributes: { pace: 92, shooting: 76, passing: 80, dribbling: 86, defending: 75, physical: 78, overall: 85 } },
        { name: 'Marquinhos', pos: 'CB', age: 29, rating: 87, attributes: { pace: 79, shooting: 55, passing: 77, dribbling: 75, defending: 89, physical: 82, overall: 87 } },
        { name: 'Milan Škriniar', pos: 'CB', age: 28, rating: 86, attributes: { pace: 73, shooting: 48, passing: 72, dribbling: 70, defending: 88, physical: 86, overall: 86 } },
        { name: 'Presnel Kimpembe', pos: 'CB', age: 27, rating: 84, attributes: { pace: 74, shooting: 42, passing: 74, dribbling: 72, defending: 85, physical: 86, overall: 84 } },
        { name: 'Nuno Mendes', pos: 'LB', age: 21, rating: 83, attributes: { pace: 92, shooting: 63, passing: 78, dribbling: 84, defending: 75, physical: 79, overall: 83 } },
        { name: 'Lucas Hernandez', pos: 'LB', age: 27, rating: 84, attributes: { pace: 81, shooting: 53, passing: 76, dribbling: 78, defending: 84, physical: 82, overall: 84 } },
        { name: 'Manuel Ugarte', pos: 'CM', age: 22, rating: 82, attributes: { pace: 76, shooting: 58, passing: 78, dribbling: 78, defending: 83, physical: 84, overall: 82 } },
        { name: 'Vitinha', pos: 'CM', age: 23, rating: 82, attributes: { pace: 77, shooting: 70, passing: 83, dribbling: 84, defending: 71, physical: 70, overall: 82 } },
        { name: 'Fabián Ruiz', pos: 'CM', age: 27, rating: 82, attributes: { pace: 67, shooting: 78, passing: 85, dribbling: 83, defending: 72, physical: 76, overall: 82 } },
        { name: 'Warren Zaïre-Emery', pos: 'CM', age: 17, rating: 78, attributes: { pace: 75, shooting: 70, passing: 78, dribbling: 80, defending: 74, physical: 79, overall: 78 } },
        { name: 'Ousmane Dembélé', pos: 'RW', age: 26, rating: 86, attributes: { pace: 93, shooting: 80, passing: 82, dribbling: 92, defending: 45, physical: 71, overall: 86 } },
        { name: 'Kylian Mbappé', pos: 'ST', age: 24, rating: 92, attributes: { pace: 97, shooting: 90, passing: 82, dribbling: 92, defending: 40, physical: 81, overall: 92 } },
        { name: 'Randal Kolo Muani', pos: 'ST', age: 24, rating: 84, attributes: { pace: 91, shooting: 81, passing: 77, dribbling: 85, defending: 47, physical: 78, overall: 84 } },
        { name: 'Gonçalo Ramos', pos: 'ST', age: 22, rating: 83, attributes: { pace: 82, shooting: 85, passing: 70, dribbling: 79, defending: 48, physical: 81, overall: 83 } },
        { name: 'Marco Asensio', pos: 'RW', age: 27, rating: 83, attributes: { pace: 79, shooting: 84, passing: 82, dribbling: 84, defending: 46, physical: 71, overall: 83 } },
        { name: 'Lee Kang-in', pos: 'AM', age: 22, rating: 80, attributes: { pace: 75, shooting: 74, passing: 83, dribbling: 86, defending: 42, physical: 65, overall: 80 } },
        { name: 'Carlos Soler', pos: 'CM', age: 26, rating: 81, attributes: { pace: 70, shooting: 80, passing: 82, dribbling: 80, defending: 68, physical: 74, overall: 81 } },
        { name: 'Danilo Pereira', pos: 'CDM', age: 31, rating: 81, attributes: { pace: 63, shooting: 68, passing: 74, dribbling: 72, defending: 83, physical: 84, overall: 81 } }
      ]
    },
    {
      code: 'mar',
      name: 'Olympique de Marseille',
      shortName: 'Marseille',
      balance: 420000,
      ticketsPrice: 25,
      sponsor: { name: 'CMA CGM', monthly: 110000 },
      players: [
        { name: 'Pau López', pos: 'GK', age: 28, rating: 82, attributes: { pace: 54, shooting: 22, passing: 73, dribbling: 65, defending: 20, physical: 72, overall: 82 } },
        { name: 'Joaquín Correa', pos: 'LW', age: 29, rating: 80, attributes: { pace: 85, shooting: 76, passing: 78, dribbling: 84, defending: 47, physical: 74, overall: 80 } },
        { name: 'Jonathan Clauss', pos: 'RB', age: 30, rating: 83, attributes: { pace: 86, shooting: 73, passing: 82, dribbling: 80, defending: 75, physical: 78, overall: 83 } },
        { name: 'Chancel Mbemba', pos: 'CB', age: 28, rating: 82, attributes: { pace: 78, shooting: 50, passing: 71, dribbling: 70, defending: 84, physical: 85, overall: 82 } },
        { name: 'Samuel Gigot', pos: 'CB', age: 29, rating: 80, attributes: { pace: 72, shooting: 48, passing: 68, dribbling: 65, defending: 82, physical: 82, overall: 80 } },
        { name: 'Leonardo Balerdi', pos: 'CB', age: 24, rating: 78, attributes: { pace: 73, shooting: 38, passing: 66, dribbling: 66, defending: 79, physical: 79, overall: 78 } },
        { name: 'Renan Lodi', pos: 'LB', age: 25, rating: 80, attributes: { pace: 86, shooting: 64, passing: 77, dribbling: 82, defending: 74, physical: 77, overall: 80 } },
        { name: 'Michael Murillo', pos: 'RB', age: 27, rating: 78, attributes: { pace: 83, shooting: 63, passing: 73, dribbling: 77, defending: 74, physical: 80, overall: 78 } },
        { name: 'Valentin Rongier', pos: 'CM', age: 28, rating: 81, attributes: { pace: 74, shooting: 69, passing: 82, dribbling: 81, defending: 78, physical: 78, overall: 81 } },
        { name: 'Jordan Veretout', pos: 'CM', age: 30, rating: 80, attributes: { pace: 74, shooting: 77, passing: 80, dribbling: 80, defending: 72, physical: 79, overall: 80 } },
        { name: 'Geoffrey Kondogbia', pos: 'CDM', age: 30, rating: 81, attributes: { pace: 68, shooting: 70, passing: 77, dribbling: 77, defending: 83, physical: 86, overall: 81 } },
        { name: 'Azzedine Ounahi', pos: 'CM', age: 23, rating: 79, attributes: { pace: 78, shooting: 72, passing: 79, dribbling: 85, defending: 68, physical: 70, overall: 79 } },
        { name: 'Pierre-Emerick Aubameyang', pos: 'ST', age: 34, rating: 82, attributes: { pace: 89, shooting: 83, passing: 71, dribbling: 79, defending: 44, physical: 73, overall: 82 } },
        { name: 'Vitinha', pos: 'ST', age: 23, rating: 78, attributes: { pace: 82, shooting: 77, passing: 68, dribbling: 79, defending: 45, physical: 71, overall: 78 } },
        { name: 'Ismaïla Sarr', pos: 'RW', age: 25, rating: 81, attributes: { pace: 94, shooting: 76, passing: 72, dribbling: 82, defending: 52, physical: 78, overall: 81 } },
        { name: 'Iliman Ndiaye', pos: 'AM', age: 23, rating: 80, attributes: { pace: 82, shooting: 76, passing: 77, dribbling: 86, defending: 52, physical: 74, overall: 80 } },
        { name: 'Amine Harit', pos: 'AM', age: 26, rating: 79, attributes: { pace: 83, shooting: 70, passing: 78, dribbling: 87, defending: 44, physical: 64, overall: 79 } },
        { name: 'Matteo Guendouzi', pos: 'CM', age: 24, rating: 80, attributes: { pace: 73, shooting: 71, passing: 80, dribbling: 80, defending: 74, physical: 80, overall: 80 } },
        { name: 'Bamo Meïté', pos: 'CB', age: 21, rating: 74, attributes: { pace: 74, shooting: 38, passing: 64, dribbling: 64, defending: 76, physical: 78, overall: 74 } }
      ]
    },
    {
      code: 'asm',
      name: 'AS Monaco',
      shortName: 'Monaco',
      balance: 460000,
      ticketsPrice: 26,
      sponsor: { name: 'Fedcom', monthly: 115000 },
      players: [
        { name: 'Philipp Köhn', pos: 'GK', age: 25, rating: 79, attributes: { pace: 56, shooting: 20, passing: 70, dribbling: 64, defending: 20, physical: 74, overall: 79 } },
        { name: 'Radoslaw Majecki', pos: 'GK', age: 23, rating: 73, attributes: { pace: 50, shooting: 18, passing: 65, dribbling: 60, defending: 18, physical: 70, overall: 73 } },
        { name: 'Caio Henrique', pos: 'LB', age: 26, rating: 82, attributes: { pace: 84, shooting: 65, passing: 84, dribbling: 82, defending: 74, physical: 74, overall: 82 } },
        { name: 'Vanderson', pos: 'RB', age: 22, rating: 79, attributes: { pace: 86, shooting: 67, passing: 75, dribbling: 80, defending: 74, physical: 78, overall: 79 } },
        { name: 'Axel Disasi', pos: 'CB', age: 25, rating: 82, attributes: { pace: 76, shooting: 53, passing: 74, dribbling: 70, defending: 83, physical: 85, overall: 82 } },
        { name: 'Guillermo Maripán', pos: 'CB', age: 29, rating: 79, attributes: { pace: 58, shooting: 52, passing: 72, dribbling: 67, defending: 81, physical: 83, overall: 79 } },
        { name: 'Thilo Kehrer', pos: 'CB', age: 26, rating: 79, attributes: { pace: 76, shooting: 50, passing: 74, dribbling: 73, defending: 80, physical: 78, overall: 79 } },
        { name: 'Youssouf Fofana', pos: 'CM', age: 24, rating: 82, attributes: { pace: 78, shooting: 71, passing: 78, dribbling: 79, defending: 78, physical: 83, overall: 82 } },
        { name: 'Denis Zakaria', pos: 'CDM', age: 26, rating: 81, attributes: { pace: 78, shooting: 66, passing: 75, dribbling: 77, defending: 82, physical: 85, overall: 81 } },
        { name: 'Mohamed Camara', pos: 'CM', age: 23, rating: 80, attributes: { pace: 78, shooting: 65, passing: 74, dribbling: 78, defending: 80, physical: 84, overall: 80 } },
        { name: 'Aleksandr Golovin', pos: 'AM', age: 27, rating: 83, attributes: { pace: 79, shooting: 80, passing: 84, dribbling: 85, defending: 63, physical: 74, overall: 83 } },
        { name: 'Takumi Minamino', pos: 'AM', age: 28, rating: 78, attributes: { pace: 82, shooting: 74, passing: 77, dribbling: 82, defending: 58, physical: 70, overall: 78 } },
        { name: 'Eliesse Ben Seghir', pos: 'AM', age: 18, rating: 75, attributes: { pace: 78, shooting: 72, passing: 74, dribbling: 82, defending: 48, physical: 66, overall: 75 } },
        { name: 'Breel Embolo', pos: 'ST', age: 26, rating: 81, attributes: { pace: 84, shooting: 80, passing: 72, dribbling: 78, defending: 48, physical: 85, overall: 81 } },
        { name: 'Wissam Ben Yedder', pos: 'ST', age: 32, rating: 84, attributes: { pace: 82, shooting: 86, passing: 78, dribbling: 87, defending: 46, physical: 70, overall: 84 } },
        { name: 'Myron Boadu', pos: 'ST', age: 22, rating: 76, attributes: { pace: 89, shooting: 75, passing: 66, dribbling: 77, defending: 34, physical: 70, overall: 76 } },
        { name: 'Maghnes Akliouche', pos: 'AM', age: 21, rating: 74, attributes: { pace: 76, shooting: 70, passing: 74, dribbling: 80, defending: 40, physical: 66, overall: 74 } },
        { name: 'Krépin Diatta', pos: 'RW', age: 24, rating: 79, attributes: { pace: 92, shooting: 73, passing: 75, dribbling: 82, defending: 58, physical: 72, overall: 79 } }
      ]
    },
    {
      code: 'rcl',
      name: 'RC Lens',
      shortName: 'Lens',
      balance: 320000,
      ticketsPrice: 23,
      sponsor: { name: 'Auchan', monthly: 90000 },
      players: [
        { name: 'Brice Samba', pos: 'GK', age: 29, rating: 83, attributes: { pace: 54, shooting: 23, passing: 75, dribbling: 70, defending: 24, physical: 80, overall: 83 } },
        { name: 'Jean-Louis Leca', pos: 'GK', age: 38, rating: 73, attributes: { pace: 42, shooting: 20, passing: 64, dribbling: 60, defending: 18, physical: 68, overall: 73 } },
        { name: 'Jonathan Gradit', pos: 'CB', age: 30, rating: 81, attributes: { pace: 77, shooting: 44, passing: 76, dribbling: 76, defending: 83, physical: 79, overall: 81 } },
        { name: 'Kevin Danso', pos: 'CB', age: 24, rating: 82, attributes: { pace: 77, shooting: 50, passing: 73, dribbling: 72, defending: 84, physical: 85, overall: 82 } },
        { name: 'Facundo Medina', pos: 'CB', age: 24, rating: 82, attributes: { pace: 78, shooting: 64, passing: 80, dribbling: 78, defending: 82, physical: 84, overall: 82 } },
        { name: 'Przemysław Frankowski', pos: 'RWB', age: 27, rating: 79, attributes: { pace: 88, shooting: 73, passing: 78, dribbling: 80, defending: 72, physical: 76, overall: 79 } },
        { name: 'Deiver Machado', pos: 'LWB', age: 29, rating: 78, attributes: { pace: 86, shooting: 69, passing: 75, dribbling: 78, defending: 72, physical: 80, overall: 78 } },
        { name: 'Ruben Aguilar', pos: 'RWB', age: 30, rating: 77, attributes: { pace: 82, shooting: 64, passing: 73, dribbling: 78, defending: 74, physical: 77, overall: 77 } },
        { name: 'Salis Abdul Samed', pos: 'CDM', age: 23, rating: 80, attributes: { pace: 76, shooting: 60, passing: 76, dribbling: 78, defending: 82, physical: 83, overall: 80 } },
        { name: 'Andy Diouf', pos: 'CM', age: 20, rating: 76, attributes: { pace: 78, shooting: 68, passing: 74, dribbling: 78, defending: 70, physical: 78, overall: 76 } },
        { name: 'Adrien Thomasson', pos: 'AM', age: 29, rating: 79, attributes: { pace: 74, shooting: 75, passing: 80, dribbling: 81, defending: 62, physical: 70, overall: 79 } },
        { name: 'David Pereira da Costa', pos: 'AM', age: 22, rating: 78, attributes: { pace: 82, shooting: 72, passing: 77, dribbling: 84, defending: 56, physical: 68, overall: 78 } },
        { name: 'Florian Sotoca', pos: 'RW', age: 32, rating: 80, attributes: { pace: 79, shooting: 78, passing: 78, dribbling: 80, defending: 63, physical: 78, overall: 80 } },
        { name: 'Angelo Fulgini', pos: 'AM', age: 27, rating: 79, attributes: { pace: 76, shooting: 77, passing: 79, dribbling: 82, defending: 62, physical: 74, overall: 79 } },
        { name: 'Elye Wahi', pos: 'ST', age: 20, rating: 80, attributes: { pace: 89, shooting: 79, passing: 70, dribbling: 81, defending: 48, physical: 78, overall: 80 } },
        { name: 'Loïs Openda', pos: 'ST', age: 23, rating: 82, attributes: { pace: 93, shooting: 80, passing: 70, dribbling: 80, defending: 46, physical: 78, overall: 82 } },
        { name: 'Morgan Guilavogui', pos: 'ST', age: 25, rating: 76, attributes: { pace: 84, shooting: 75, passing: 66, dribbling: 75, defending: 45, physical: 76, overall: 76 } },
        { name: 'Wesley Saïd', pos: 'ST', age: 28, rating: 75, attributes: { pace: 84, shooting: 74, passing: 68, dribbling: 78, defending: 40, physical: 70, overall: 75 } }
      ]
    },
    {
      code: 'losc',
      name: 'LOSC Lille',
      shortName: 'Lille',
      balance: 310000,
      ticketsPrice: 22,
      sponsor: { name: 'Partouche', monthly: 85000 },
      players: [
        { name: 'Lucas Chevalier', pos: 'GK', age: 21, rating: 80, attributes: { pace: 52, shooting: 20, passing: 71, dribbling: 68, defending: 24, physical: 75, overall: 80 } },
        { name: 'Vito Mannone', pos: 'GK', age: 35, rating: 74, attributes: { pace: 44, shooting: 18, passing: 65, dribbling: 60, defending: 18, physical: 70, overall: 74 } },
        { name: 'Tiago Djaló', pos: 'CB', age: 23, rating: 78, attributes: { pace: 81, shooting: 46, passing: 70, dribbling: 70, defending: 80, physical: 84, overall: 78 } },
        { name: 'Alexsandro', pos: 'CB', age: 24, rating: 76, attributes: { pace: 73, shooting: 50, passing: 68, dribbling: 68, defending: 78, physical: 82, overall: 76 } },
        { name: 'Bafodé Diakité', pos: 'RB', age: 22, rating: 77, attributes: { pace: 80, shooting: 58, passing: 72, dribbling: 74, defending: 77, physical: 80, overall: 77 } },
        { name: 'Gabriel Gudmundsson', pos: 'LB', age: 24, rating: 76, attributes: { pace: 86, shooting: 62, passing: 74, dribbling: 78, defending: 71, physical: 76, overall: 76 } },
        { name: 'Ismaily', pos: 'LB', age: 33, rating: 79, attributes: { pace: 78, shooting: 70, passing: 79, dribbling: 80, defending: 74, physical: 78, overall: 79 } },
        { name: 'Benjamin André', pos: 'CDM', age: 32, rating: 81, attributes: { pace: 70, shooting: 66, passing: 78, dribbling: 76, defending: 83, physical: 82, overall: 81 } },
        { name: 'Angel Gomes', pos: 'CM', age: 21, rating: 79, attributes: { pace: 78, shooting: 72, passing: 82, dribbling: 84, defending: 63, physical: 62, overall: 79 } },
        { name: 'Nabil Bentaleb', pos: 'CM', age: 28, rating: 79, attributes: { pace: 71, shooting: 74, passing: 81, dribbling: 80, defending: 70, physical: 76, overall: 79 } },
        { name: 'André Gomes', pos: 'CM', age: 29, rating: 79, attributes: { pace: 65, shooting: 77, passing: 82, dribbling: 80, defending: 68, physical: 76, overall: 79 } },
        { name: 'Rémy Cabella', pos: 'AM', age: 33, rating: 80, attributes: { pace: 77, shooting: 77, passing: 82, dribbling: 85, defending: 52, physical: 66, overall: 80 } },
        { name: 'Edon Zhegrova', pos: 'RW', age: 24, rating: 79, attributes: { pace: 86, shooting: 75, passing: 76, dribbling: 87, defending: 45, physical: 68, overall: 79 } },
        { name: 'Jonathan Bamba', pos: 'LW', age: 27, rating: 80, attributes: { pace: 87, shooting: 75, passing: 77, dribbling: 83, defending: 45, physical: 72, overall: 80 } },
        { name: 'Jonathan David', pos: 'ST', age: 23, rating: 83, attributes: { pace: 87, shooting: 84, passing: 74, dribbling: 83, defending: 45, physical: 77, overall: 83 } },
        { name: 'Mohamed Bayo', pos: 'ST', age: 25, rating: 77, attributes: { pace: 78, shooting: 77, passing: 66, dribbling: 75, defending: 40, physical: 82, overall: 77 } },
        { name: 'Alan Virginius', pos: 'LW', age: 20, rating: 73, attributes: { pace: 88, shooting: 68, passing: 68, dribbling: 80, defending: 36, physical: 60, overall: 73 } },
        { name: 'Hakon Haraldsson', pos: 'AM', age: 20, rating: 74, attributes: { pace: 76, shooting: 72, passing: 74, dribbling: 78, defending: 48, physical: 66, overall: 74 } }
      ]
    },
    {
      code: 'srfc',
      name: 'Stade Rennais FC',
      shortName: 'Rennes',
      balance: 300000,
      ticketsPrice: 22,
      sponsor: { name: 'Samsic', monthly: 82000 },
      players: [
        { name: 'Steve Mandanda', pos: 'GK', age: 38, rating: 82, attributes: { pace: 43, shooting: 20, passing: 74, dribbling: 70, defending: 18, physical: 70, overall: 82 } },
        { name: 'Dogan Alemdar', pos: 'GK', age: 20, rating: 74, attributes: { pace: 48, shooting: 18, passing: 63, dribbling: 62, defending: 16, physical: 70, overall: 74 } },
        { name: 'Hamari Traoré', pos: 'RB', age: 31, rating: 82, attributes: { pace: 87, shooting: 67, passing: 80, dribbling: 80, defending: 78, physical: 81, overall: 82 } },
        { name: 'Arthur Theate', pos: 'CB', age: 23, rating: 81, attributes: { pace: 77, shooting: 54, passing: 76, dribbling: 74, defending: 82, physical: 82, overall: 81 } },
        { name: 'Warmed Omari', pos: 'CB', age: 23, rating: 78, attributes: { pace: 75, shooting: 46, passing: 72, dribbling: 72, defending: 78, physical: 79, overall: 78 } },
        { name: 'Christopher Wooh', pos: 'CB', age: 21, rating: 77, attributes: { pace: 75, shooting: 45, passing: 70, dribbling: 68, defending: 79, physical: 82, overall: 77 } },
        { name: 'Adrien Truffert', pos: 'LB', age: 21, rating: 79, attributes: { pace: 86, shooting: 63, passing: 77, dribbling: 80, defending: 74, physical: 76, overall: 79 } },
        { name: 'Lorenz Assignon', pos: 'RB', age: 23, rating: 76, attributes: { pace: 86, shooting: 60, passing: 72, dribbling: 76, defending: 70, physical: 78, overall: 76 } },
        { name: 'Benjamin Bourigeaud', pos: 'CM', age: 29, rating: 83, attributes: { pace: 74, shooting: 82, passing: 86, dribbling: 82, defending: 67, physical: 76, overall: 83 } },
        { name: 'Lovro Majer', pos: 'AM', age: 25, rating: 82, attributes: { pace: 77, shooting: 77, passing: 85, dribbling: 86, defending: 60, physical: 70, overall: 82 } },
        { name: 'Baptiste Santamaria', pos: 'CDM', age: 28, rating: 80, attributes: { pace: 70, shooting: 69, passing: 78, dribbling: 76, defending: 80, physical: 81, overall: 80 } },
        { name: 'Darline Yongwa', pos: 'LB', age: 22, rating: 75, attributes: { pace: 84, shooting: 58, passing: 72, dribbling: 76, defending: 72, physical: 76, overall: 75 } },
        { name: 'Flavien Tait', pos: 'CM', age: 30, rating: 79, attributes: { pace: 72, shooting: 74, passing: 79, dribbling: 80, defending: 66, physical: 74, overall: 79 } },
        { name: 'Jérémy Doku', pos: 'RW', age: 21, rating: 81, attributes: { pace: 94, shooting: 74, passing: 74, dribbling: 90, defending: 45, physical: 73, overall: 81 } },
        { name: 'Arnaud Kalimuendo', pos: 'ST', age: 21, rating: 78, attributes: { pace: 84, shooting: 78, passing: 70, dribbling: 80, defending: 42, physical: 72, overall: 78 } },
        { name: 'Amine Gouiri', pos: 'ST', age: 23, rating: 82, attributes: { pace: 82, shooting: 82, passing: 80, dribbling: 85, defending: 48, physical: 74, overall: 82 } },
        { name: 'Martin Terrier', pos: 'LW', age: 26, rating: 83, attributes: { pace: 84, shooting: 84, passing: 80, dribbling: 85, defending: 50, physical: 78, overall: 83 } },
        { name: 'Ibrahim Salah', pos: 'LW', age: 21, rating: 73, attributes: { pace: 85, shooting: 66, passing: 68, dribbling: 76, defending: 36, physical: 66, overall: 73 } }
      ]
    },
    {
      code: 'ogcn',
      name: 'OGC Nice',
      shortName: 'Nice',
      balance: 290000,
      ticketsPrice: 21,
      sponsor: { name: 'INEOS', monthly: 78000 },
      players: [
        { name: 'Kasper Schmeichel', pos: 'GK', age: 36, rating: 82, attributes: { pace: 46, shooting: 26, passing: 74, dribbling: 70, defending: 22, physical: 72, overall: 82 } },
        { name: 'Marcin Bułka', pos: 'GK', age: 23, rating: 77, attributes: { pace: 51, shooting: 20, passing: 66, dribbling: 62, defending: 20, physical: 72, overall: 77 } },
        { name: 'Youcef Atal', pos: 'RB', age: 27, rating: 78, attributes: { pace: 91, shooting: 69, passing: 74, dribbling: 82, defending: 69, physical: 74, overall: 78 } },
        { name: 'Jordan Lotomba', pos: 'RB', age: 24, rating: 77, attributes: { pace: 86, shooting: 63, passing: 73, dribbling: 79, defending: 70, physical: 76, overall: 77 } },
        { name: 'Jean-Clair Todibo', pos: 'CB', age: 23, rating: 81, attributes: { pace: 79, shooting: 52, passing: 76, dribbling: 76, defending: 83, physical: 82, overall: 81 } },
        { name: 'Dante', pos: 'CB', age: 39, rating: 80, attributes: { pace: 44, shooting: 62, passing: 82, dribbling: 78, defending: 85, physical: 79, overall: 80 } },
        { name: 'Melvin Bard', pos: 'LB', age: 22, rating: 78, attributes: { pace: 82, shooting: 63, passing: 75, dribbling: 78, defending: 76, physical: 76, overall: 78 } },
        { name: 'Khephren Thuram', pos: 'CM', age: 22, rating: 82, attributes: { pace: 81, shooting: 76, passing: 80, dribbling: 83, defending: 75, physical: 86, overall: 82 } },
        { name: 'Youssouf Ndayishimiye', pos: 'CDM', age: 24, rating: 79, attributes: { pace: 74, shooting: 68, passing: 76, dribbling: 76, defending: 78, physical: 83, overall: 79 } },
        { name: 'Pablo Rosario', pos: 'CDM', age: 26, rating: 78, attributes: { pace: 72, shooting: 65, passing: 76, dribbling: 76, defending: 78, physical: 81, overall: 78 } },
        { name: 'Aaron Ramsey', pos: 'CM', age: 32, rating: 79, attributes: { pace: 67, shooting: 78, passing: 80, dribbling: 79, defending: 70, physical: 74, overall: 79 } },
        { name: 'Hicham Boudaoui', pos: 'CM', age: 23, rating: 79, attributes: { pace: 80, shooting: 72, passing: 78, dribbling: 82, defending: 69, physical: 74, overall: 79 } },
        { name: 'Gaëtan Laborde', pos: 'ST', age: 29, rating: 80, attributes: { pace: 78, shooting: 82, passing: 73, dribbling: 78, defending: 52, physical: 80, overall: 80 } },
        { name: 'Terem Moffi', pos: 'ST', age: 24, rating: 81, attributes: { pace: 86, shooting: 82, passing: 69, dribbling: 78, defending: 46, physical: 84, overall: 81 } },
        { name: 'Sofiane Diop', pos: 'LW', age: 22, rating: 80, attributes: { pace: 84, shooting: 74, passing: 78, dribbling: 85, defending: 50, physical: 70, overall: 80 } },
        { name: 'Nicolas Pépé', pos: 'RW', age: 28, rating: 81, attributes: { pace: 86, shooting: 82, passing: 78, dribbling: 85, defending: 46, physical: 74, overall: 81 } },
        { name: 'Alexis Claude-Maurice', pos: 'AM', age: 24, rating: 77, attributes: { pace: 79, shooting: 73, passing: 78, dribbling: 82, defending: 55, physical: 68, overall: 77 } },
        { name: 'Badredine Bouanani', pos: 'RW', age: 18, rating: 72, attributes: { pace: 84, shooting: 68, passing: 70, dribbling: 80, defending: 35, physical: 60, overall: 72 } }
      ]
    },
    {
      code: 'ol',
      name: 'Olympique Lyonnais',
      shortName: 'Lyon',
      balance: 350000,
      ticketsPrice: 24,
      sponsor: { name: 'Emirates', monthly: 95000 },
      players: [
        { name: 'Anthony Lopes', pos: 'GK', age: 32, rating: 82, attributes: { pace: 53, shooting: 25, passing: 74, dribbling: 70, defending: 20, physical: 75, overall: 82 } },
        { name: 'Rémy Riou', pos: 'GK', age: 36, rating: 72, attributes: { pace: 45, shooting: 20, passing: 63, dribbling: 60, defending: 18, physical: 66, overall: 72 } },
        { name: 'Nicolás Tagliafico', pos: 'LB', age: 31, rating: 83, attributes: { pace: 79, shooting: 65, passing: 80, dribbling: 80, defending: 82, physical: 80, overall: 83 } },
        { name: 'Clinton Mata', pos: 'RB', age: 30, rating: 80, attributes: { pace: 82, shooting: 65, passing: 75, dribbling: 78, defending: 79, physical: 80, overall: 80 } },
        { name: 'Dejan Lovren', pos: 'CB', age: 34, rating: 79, attributes: { pace: 55, shooting: 54, passing: 72, dribbling: 70, defending: 82, physical: 83, overall: 79 } },
        { name: 'Jake O’Brien', pos: 'CB', age: 22, rating: 75, attributes: { pace: 72, shooting: 48, passing: 68, dribbling: 66, defending: 76, physical: 78, overall: 75 } },
        { name: 'Castello Lukeba', pos: 'CB', age: 20, rating: 79, attributes: { pace: 76, shooting: 44, passing: 72, dribbling: 72, defending: 80, physical: 80, overall: 79 } },
        { name: 'Saël Kumbedi', pos: 'RB', age: 18, rating: 74, attributes: { pace: 82, shooting: 52, passing: 68, dribbling: 75, defending: 70, physical: 74, overall: 74 } },
        { name: 'Maxence Caqueret', pos: 'CM', age: 23, rating: 81, attributes: { pace: 77, shooting: 68, passing: 83, dribbling: 83, defending: 75, physical: 75, overall: 81 } },
        { name: 'Corentin Tolisso', pos: 'CM', age: 29, rating: 81, attributes: { pace: 66, shooting: 79, passing: 83, dribbling: 80, defending: 74, physical: 81, overall: 81 } },
        { name: 'Johann Lepenant', pos: 'CDM', age: 20, rating: 76, attributes: { pace: 74, shooting: 60, passing: 74, dribbling: 76, defending: 76, physical: 76, overall: 76 } },
        { name: 'Rayan Cherki', pos: 'AM', age: 20, rating: 79, attributes: { pace: 80, shooting: 78, passing: 82, dribbling: 88, defending: 40, physical: 70, overall: 79 } },
        { name: 'Ainsley Maitland-Niles', pos: 'CM', age: 25, rating: 77, attributes: { pace: 82, shooting: 68, passing: 75, dribbling: 80, defending: 73, physical: 78, overall: 77 } },
        { name: 'Alexandre Lacazette', pos: 'ST', age: 32, rating: 84, attributes: { pace: 74, shooting: 85, passing: 78, dribbling: 80, defending: 45, physical: 78, overall: 84 } },
        { name: 'Bradley Barcola', pos: 'LW', age: 21, rating: 78, attributes: { pace: 86, shooting: 74, passing: 75, dribbling: 83, defending: 45, physical: 70, overall: 78 } },
        { name: 'Ernest Nuamah', pos: 'RW', age: 19, rating: 78, attributes: { pace: 91, shooting: 76, passing: 74, dribbling: 84, defending: 42, physical: 74, overall: 78 } },
        { name: 'Tino Kadewere', pos: 'ST', age: 27, rating: 75, attributes: { pace: 81, shooting: 75, passing: 66, dribbling: 76, defending: 38, physical: 74, overall: 75 } },
        { name: 'Gift Orban', pos: 'ST', age: 21, rating: 77, attributes: { pace: 86, shooting: 79, passing: 68, dribbling: 80, defending: 40, physical: 74, overall: 77 } }
      ]
    },
    {
      code: 'mhsc',
      name: 'Montpellier HSC',
      shortName: 'Montpellier',
      balance: 210000,
      ticketsPrice: 18,
      sponsor: { name: 'Sud de France', monthly: 60000 },
      players: [
        { name: 'Benjamin Lecomte', pos: 'GK', age: 32, rating: 80, attributes: { pace: 51, shooting: 22, passing: 72, dribbling: 68, defending: 18, physical: 75, overall: 80 } },
        { name: 'Dimitry Bertaud', pos: 'GK', age: 25, rating: 74, attributes: { pace: 48, shooting: 18, passing: 64, dribbling: 60, defending: 18, physical: 70, overall: 74 } },
        { name: 'Enzo Tchato', pos: 'RB', age: 20, rating: 73, attributes: { pace: 82, shooting: 54, passing: 70, dribbling: 74, defending: 70, physical: 74, overall: 73 } },
        { name: 'Falaye Sacko', pos: 'RB', age: 28, rating: 76, attributes: { pace: 83, shooting: 58, passing: 72, dribbling: 74, defending: 75, physical: 80, overall: 76 } },
        { name: 'Christopher Jullien', pos: 'CB', age: 30, rating: 76, attributes: { pace: 55, shooting: 53, passing: 68, dribbling: 66, defending: 79, physical: 83, overall: 76 } },
        { name: 'Maxime Estève', pos: 'CB', age: 21, rating: 75, attributes: { pace: 72, shooting: 44, passing: 68, dribbling: 68, defending: 76, physical: 78, overall: 75 } },
        { name: 'Becir Omeragic', pos: 'CB', age: 21, rating: 74, attributes: { pace: 73, shooting: 45, passing: 68, dribbling: 68, defending: 75, physical: 76, overall: 74 } },
        { name: 'Issiaga Sylla', pos: 'LB', age: 29, rating: 75, attributes: { pace: 82, shooting: 60, passing: 74, dribbling: 76, defending: 72, physical: 78, overall: 75 } },
        { name: 'Jordan Ferri', pos: 'CM', age: 31, rating: 77, attributes: { pace: 71, shooting: 66, passing: 78, dribbling: 76, defending: 74, physical: 78, overall: 77 } },
        { name: 'Joris Chotard', pos: 'CDM', age: 21, rating: 77, attributes: { pace: 73, shooting: 60, passing: 76, dribbling: 75, defending: 78, physical: 78, overall: 77 } },
        { name: 'Téji Savanier', pos: 'AM', age: 31, rating: 82, attributes: { pace: 70, shooting: 82, passing: 87, dribbling: 84, defending: 60, physical: 72, overall: 82 } },
        { name: 'Mousa Tamari', pos: 'RW', age: 26, rating: 78, attributes: { pace: 88, shooting: 75, passing: 74, dribbling: 82, defending: 46, physical: 72, overall: 78 } },
        { name: 'Wahbi Khazri', pos: 'ST', age: 32, rating: 78, attributes: { pace: 72, shooting: 80, passing: 78, dribbling: 80, defending: 45, physical: 76, overall: 78 } },
        { name: 'Akor Adams', pos: 'ST', age: 23, rating: 77, attributes: { pace: 82, shooting: 78, passing: 66, dribbling: 74, defending: 45, physical: 82, overall: 77 } },
        { name: 'Arnaud Nordin', pos: 'LW', age: 25, rating: 78, attributes: { pace: 89, shooting: 74, passing: 72, dribbling: 82, defending: 48, physical: 72, overall: 78 } },
        { name: 'Stephy Mavididi', pos: 'LW', age: 25, rating: 79, attributes: { pace: 90, shooting: 77, passing: 74, dribbling: 84, defending: 48, physical: 73, overall: 79 } },
        { name: 'Khalil Fayad', pos: 'CM', age: 19, rating: 72, attributes: { pace: 76, shooting: 64, passing: 72, dribbling: 78, defending: 52, physical: 64, overall: 72 } },
        { name: 'Léo Leroy', pos: 'CM', age: 23, rating: 74, attributes: { pace: 72, shooting: 64, passing: 75, dribbling: 76, defending: 66, physical: 72, overall: 74 } }
      ]
    },
    {
      code: 'sdr',
      name: 'Stade de Reims',
      shortName: 'Reims',
      balance: 230000,
      ticketsPrice: 19,
      sponsor: { name: 'Maison France Confort', monthly: 62000 },
      players: [
        { name: 'Yehvann Diouf', pos: 'GK', age: 23, rating: 77, attributes: { pace: 55, shooting: 20, passing: 70, dribbling: 66, defending: 20, physical: 74, overall: 77 } },
        { name: 'Patrick Pentz', pos: 'GK', age: 26, rating: 75, attributes: { pace: 50, shooting: 18, passing: 68, dribbling: 64, defending: 18, physical: 72, overall: 75 } },
        { name: 'Thomas Foket', pos: 'RB', age: 28, rating: 78, attributes: { pace: 82, shooting: 60, passing: 76, dribbling: 76, defending: 76, physical: 78, overall: 78 } },
        { name: 'Thibault De Smet', pos: 'LB', age: 25, rating: 76, attributes: { pace: 80, shooting: 58, passing: 74, dribbling: 76, defending: 72, physical: 74, overall: 76 } },
        { name: 'Yunis Abdelhamid', pos: 'CB', age: 35, rating: 78, attributes: { pace: 60, shooting: 49, passing: 72, dribbling: 68, defending: 80, physical: 82, overall: 78 } },
        { name: 'Emmanuel Agbadou', pos: 'CB', age: 26, rating: 77, attributes: { pace: 72, shooting: 46, passing: 70, dribbling: 68, defending: 78, physical: 82, overall: 77 } },
        { name: 'Joseph Okumu', pos: 'CB', age: 26, rating: 76, attributes: { pace: 76, shooting: 45, passing: 70, dribbling: 70, defending: 77, physical: 80, overall: 76 } },
        { name: 'Azor Matusiwa', pos: 'CDM', age: 25, rating: 79, attributes: { pace: 74, shooting: 62, passing: 76, dribbling: 78, defending: 80, physical: 82, overall: 79 } },
        { name: 'Jens Cajuste', pos: 'CM', age: 24, rating: 78, attributes: { pace: 74, shooting: 68, passing: 76, dribbling: 78, defending: 74, physical: 82, overall: 78 } },
        { name: 'Marshall Munetsi', pos: 'CM', age: 27, rating: 79, attributes: { pace: 76, shooting: 72, passing: 75, dribbling: 77, defending: 78, physical: 85, overall: 79 } },
        { name: 'Arber Zeneli', pos: 'LW', age: 28, rating: 77, attributes: { pace: 83, shooting: 72, passing: 76, dribbling: 82, defending: 40, physical: 69, overall: 77 } },
        { name: 'Jun-ya Ito', pos: 'RW', age: 30, rating: 80, attributes: { pace: 94, shooting: 74, passing: 78, dribbling: 82, defending: 55, physical: 72, overall: 80 } },
        { name: 'Alexis Flips', pos: 'AM', age: 23, rating: 77, attributes: { pace: 76, shooting: 70, passing: 78, dribbling: 82, defending: 48, physical: 70, overall: 77 } },
        { name: 'Teddy Teuma', pos: 'CM', age: 29, rating: 79, attributes: { pace: 72, shooting: 78, passing: 82, dribbling: 80, defending: 66, physical: 74, overall: 79 } },
        { name: 'Keito Nakamura', pos: 'LW', age: 23, rating: 78, attributes: { pace: 87, shooting: 76, passing: 74, dribbling: 82, defending: 45, physical: 72, overall: 78 } },
        { name: 'Folarin Balogun', pos: 'ST', age: 22, rating: 81, attributes: { pace: 87, shooting: 82, passing: 72, dribbling: 80, defending: 45, physical: 76, overall: 81 } },
        { name: 'Ibrahim Salah', pos: 'LW', age: 21, rating: 73, attributes: { pace: 86, shooting: 66, passing: 68, dribbling: 76, defending: 36, physical: 66, overall: 73 } },
        { name: 'Mamadou Diakhon', pos: 'ST', age: 19, rating: 72, attributes: { pace: 82, shooting: 70, passing: 62, dribbling: 72, defending: 35, physical: 70, overall: 72 } }
      ]
    },
    {
      code: 'fcl',
      name: 'FC Lorient',
      shortName: 'Lorient',
      balance: 190000,
      ticketsPrice: 17,
      sponsor: { name: 'Actual', monthly: 54000 },
      players: [
        { name: 'Yvon Mvogo', pos: 'GK', age: 29, rating: 79, attributes: { pace: 54, shooting: 20, passing: 72, dribbling: 68, defending: 20, physical: 75, overall: 79 } },
        { name: 'Gédéon Kalulu', pos: 'RB', age: 25, rating: 76, attributes: { pace: 84, shooting: 58, passing: 74, dribbling: 76, defending: 74, physical: 78, overall: 76 } },
        { name: 'Igor Silva', pos: 'RB', age: 26, rating: 75, attributes: { pace: 82, shooting: 58, passing: 72, dribbling: 76, defending: 72, physical: 76, overall: 75 } },
        { name: 'Montassar Talbi', pos: 'CB', age: 25, rating: 79, attributes: { pace: 73, shooting: 48, passing: 74, dribbling: 72, defending: 80, physical: 80, overall: 79 } },
        { name: 'Bamo Meïté', pos: 'CB', age: 21, rating: 74, attributes: { pace: 74, shooting: 38, passing: 64, dribbling: 64, defending: 76, physical: 78, overall: 74 } },
        { name: 'Vincent Le Goff', pos: 'LB', age: 33, rating: 75, attributes: { pace: 76, shooting: 60, passing: 75, dribbling: 76, defending: 74, physical: 76, overall: 75 } },
        { name: 'Laurent Abergel', pos: 'CDM', age: 30, rating: 78, attributes: { pace: 74, shooting: 60, passing: 75, dribbling: 76, defending: 80, physical: 80, overall: 78 } },
        { name: 'Bonke Innocent', pos: 'CDM', age: 27, rating: 75, attributes: { pace: 71, shooting: 56, passing: 70, dribbling: 70, defending: 76, physical: 80, overall: 75 } },
        { name: 'Julien Ponceau', pos: 'CM', age: 22, rating: 74, attributes: { pace: 74, shooting: 64, passing: 74, dribbling: 76, defending: 66, physical: 70, overall: 74 } },
        { name: 'Romain Faivre', pos: 'RW', age: 24, rating: 78, attributes: { pace: 82, shooting: 76, passing: 79, dribbling: 84, defending: 45, physical: 70, overall: 78 } },
        { name: 'Yoann Cathline', pos: 'LW', age: 21, rating: 73, attributes: { pace: 85, shooting: 66, passing: 70, dribbling: 78, defending: 40, physical: 68, overall: 73 } },
        { name: 'Théo Le Bris', pos: 'AM', age: 21, rating: 74, attributes: { pace: 78, shooting: 70, passing: 74, dribbling: 80, defending: 45, physical: 68, overall: 74 } },
        { name: 'Bamba Dieng', pos: 'ST', age: 22, rating: 77, attributes: { pace: 86, shooting: 77, passing: 66, dribbling: 76, defending: 45, physical: 76, overall: 77 } },
        { name: 'Ibrahim Koné', pos: 'ST', age: 24, rating: 75, attributes: { pace: 78, shooting: 76, passing: 64, dribbling: 74, defending: 40, physical: 80, overall: 75 } },
        { name: 'Siriné Doucouré', pos: 'ST', age: 21, rating: 72, attributes: { pace: 80, shooting: 72, passing: 62, dribbling: 72, defending: 38, physical: 72, overall: 72 } },
        { name: 'Adil Aouchiche', pos: 'AM', age: 21, rating: 73, attributes: { pace: 74, shooting: 66, passing: 74, dribbling: 78, defending: 40, physical: 66, overall: 73 } },
        { name: 'Quentin Boisgard', pos: 'CM', age: 26, rating: 72, attributes: { pace: 72, shooting: 66, passing: 72, dribbling: 74, defending: 64, physical: 68, overall: 72 } }
      ]
    },
    {
      code: 'tfc',
      name: 'Toulouse FC',
      shortName: 'Toulouse',
      balance: 200000,
      ticketsPrice: 18,
      sponsor: { name: 'Newrest', monthly: 56000 },
      players: [
        { name: 'Guillaume Restes', pos: 'GK', age: 18, rating: 75, attributes: { pace: 53, shooting: 18, passing: 68, dribbling: 64, defending: 18, physical: 72, overall: 75 } },
        { name: 'Alex Domínguez', pos: 'GK', age: 27, rating: 73, attributes: { pace: 49, shooting: 18, passing: 66, dribbling: 62, defending: 16, physical: 70, overall: 73 } },
        { name: 'Gabriel Suazo', pos: 'LB', age: 25, rating: 77, attributes: { pace: 84, shooting: 62, passing: 74, dribbling: 78, defending: 74, physical: 78, overall: 77 } },
        { name: 'Mikkel Desler', pos: 'RB', age: 28, rating: 76, attributes: { pace: 82, shooting: 58, passing: 74, dribbling: 76, defending: 74, physical: 78, overall: 76 } },
        { name: 'Logan Costa', pos: 'CB', age: 22, rating: 75, attributes: { pace: 73, shooting: 48, passing: 70, dribbling: 70, defending: 76, physical: 80, overall: 75 } },
        { name: 'Rasmus Nicolaisen', pos: 'CB', age: 26, rating: 76, attributes: { pace: 69, shooting: 50, passing: 72, dribbling: 68, defending: 78, physical: 82, overall: 76 } },
        { name: 'Waren Kamanzi', pos: 'RB', age: 22, rating: 73, attributes: { pace: 82, shooting: 55, passing: 70, dribbling: 74, defending: 68, physical: 74, overall: 73 } },
        { name: 'Stijn Spierings', pos: 'CDM', age: 27, rating: 78, attributes: { pace: 72, shooting: 75, passing: 78, dribbling: 76, defending: 76, physical: 78, overall: 78 } },
        { name: 'Vincent Sierro', pos: 'CM', age: 28, rating: 77, attributes: { pace: 70, shooting: 74, passing: 80, dribbling: 78, defending: 70, physical: 76, overall: 77 } },
        { name: 'Branco van den Boomen', pos: 'CM', age: 28, rating: 80, attributes: { pace: 72, shooting: 78, passing: 85, dribbling: 80, defending: 66, physical: 75, overall: 80 } },
        { name: 'Farès Chaïbi', pos: 'AM', age: 20, rating: 78, attributes: { pace: 82, shooting: 76, passing: 79, dribbling: 82, defending: 52, physical: 72, overall: 78 } },
        { name: 'Zakaria Aboukhlal', pos: 'RW', age: 23, rating: 79, attributes: { pace: 87, shooting: 78, passing: 74, dribbling: 82, defending: 50, physical: 76, overall: 79 } },
        { name: 'Thijs Dallinga', pos: 'ST', age: 22, rating: 79, attributes: { pace: 78, shooting: 81, passing: 70, dribbling: 76, defending: 42, physical: 80, overall: 79 } },
        { name: 'Ibrahim Cissoko', pos: 'LW', age: 20, rating: 73, attributes: { pace: 88, shooting: 68, passing: 70, dribbling: 80, defending: 36, physical: 68, overall: 73 } },
        { name: 'Cristian Cásseres Jr.', pos: 'CM', age: 23, rating: 76, attributes: { pace: 74, shooting: 68, passing: 76, dribbling: 76, defending: 72, physical: 76, overall: 76 } },
        { name: 'Denis Genreau', pos: 'CM', age: 24, rating: 74, attributes: { pace: 72, shooting: 66, passing: 75, dribbling: 75, defending: 64, physical: 70, overall: 74 } },
        { name: 'Frank Magri', pos: 'ST', age: 23, rating: 74, attributes: { pace: 80, shooting: 76, passing: 66, dribbling: 74, defending: 42, physical: 74, overall: 74 } }
      ]
    },
    {
      code: 'fcn',
      name: 'FC Nantes',
      shortName: 'Nantes',
      balance: 205000,
      ticketsPrice: 18,
      sponsor: { name: 'Synergie', monthly: 55000 },
      players: [
        { name: 'Alban Lafont', pos: 'GK', age: 24, rating: 80, attributes: { pace: 59, shooting: 24, passing: 72, dribbling: 70, defending: 24, physical: 74, overall: 80 } },
        { name: 'Rémy Descamps', pos: 'GK', age: 27, rating: 72, attributes: { pace: 48, shooting: 18, passing: 64, dribbling: 60, defending: 18, physical: 68, overall: 72 } },
        { name: 'Jean-Charles Castelletto', pos: 'CB', age: 28, rating: 78, attributes: { pace: 74, shooting: 52, passing: 72, dribbling: 70, defending: 80, physical: 82, overall: 78 } },
        { name: 'Nicolás Pallois', pos: 'CB', age: 35, rating: 77, attributes: { pace: 58, shooting: 48, passing: 68, dribbling: 64, defending: 80, physical: 84, overall: 77 } },
        { name: 'Andrei Girotto', pos: 'CB', age: 31, rating: 78, attributes: { pace: 70, shooting: 65, passing: 74, dribbling: 72, defending: 79, physical: 82, overall: 78 } },
        { name: 'Quentin Merlin', pos: 'LB', age: 21, rating: 77, attributes: { pace: 84, shooting: 66, passing: 78, dribbling: 80, defending: 72, physical: 74, overall: 77 } },
        { name: 'Fábio', pos: 'RB', age: 33, rating: 75, attributes: { pace: 82, shooting: 58, passing: 74, dribbling: 78, defending: 72, physical: 74, overall: 75 } },
        { name: 'Dennis Appiah', pos: 'RB', age: 31, rating: 74, attributes: { pace: 78, shooting: 55, passing: 72, dribbling: 74, defending: 74, physical: 74, overall: 74 } },
        { name: 'Pedro Chirivella', pos: 'CDM', age: 26, rating: 79, attributes: { pace: 70, shooting: 66, passing: 82, dribbling: 78, defending: 76, physical: 76, overall: 79 } },
        { name: 'Samuel Moutoussamy', pos: 'CM', age: 26, rating: 77, attributes: { pace: 76, shooting: 68, passing: 74, dribbling: 78, defending: 76, physical: 80, overall: 77 } },
        { name: 'Florent Mollet', pos: 'AM', age: 31, rating: 78, attributes: { pace: 72, shooting: 78, passing: 82, dribbling: 82, defending: 52, physical: 70, overall: 78 } },
        { name: 'Moses Simon', pos: 'LW', age: 27, rating: 80, attributes: { pace: 93, shooting: 74, passing: 76, dribbling: 84, defending: 48, physical: 72, overall: 80 } },
        { name: 'Ludovic Blas', pos: 'RW', age: 25, rating: 80, attributes: { pace: 82, shooting: 80, passing: 80, dribbling: 84, defending: 52, physical: 72, overall: 80 } },
        { name: 'Mostafa Mohamed', pos: 'ST', age: 25, rating: 78, attributes: { pace: 78, shooting: 80, passing: 68, dribbling: 76, defending: 46, physical: 82, overall: 78 } },
        { name: 'Ignatius Ganago', pos: 'ST', age: 24, rating: 76, attributes: { pace: 82, shooting: 76, passing: 66, dribbling: 74, defending: 44, physical: 80, overall: 76 } },
        { name: 'Andy Delort', pos: 'ST', age: 31, rating: 79, attributes: { pace: 78, shooting: 81, passing: 72, dribbling: 76, defending: 48, physical: 84, overall: 79 } },
        { name: 'Evann Guessand', pos: 'ST', age: 22, rating: 74, attributes: { pace: 80, shooting: 74, passing: 64, dribbling: 74, defending: 40, physical: 78, overall: 74 } },
        { name: 'Roli Pereira de Sa', pos: 'CM', age: 24, rating: 72, attributes: { pace: 72, shooting: 62, passing: 72, dribbling: 74, defending: 64, physical: 70, overall: 72 } }
      ]
    },
    {
      code: 'rcsa',
      name: 'RC Strasbourg Alsace',
      shortName: 'Strasbourg',
      balance: 215000,
      ticketsPrice: 18,
      sponsor: { name: 'Hager', monthly: 56000 },
      players: [
        { name: 'Matz Sels', pos: 'GK', age: 31, rating: 79, attributes: { pace: 54, shooting: 20, passing: 72, dribbling: 68, defending: 20, physical: 75, overall: 79 } },
        { name: 'Alessio Cassaro', pos: 'GK', age: 22, rating: 69, attributes: { pace: 48, shooting: 16, passing: 62, dribbling: 60, defending: 16, physical: 66, overall: 69 } },
        { name: 'Thomas Delaine', pos: 'LB', age: 31, rating: 76, attributes: { pace: 82, shooting: 62, passing: 74, dribbling: 76, defending: 72, physical: 76, overall: 76 } },
        { name: 'Maxime Le Marchand', pos: 'CB', age: 33, rating: 74, attributes: { pace: 56, shooting: 52, passing: 70, dribbling: 68, defending: 76, physical: 78, overall: 74 } },
        { name: 'Gerzino Nyamsi', pos: 'CB', age: 26, rating: 77, attributes: { pace: 74, shooting: 45, passing: 72, dribbling: 70, defending: 78, physical: 83, overall: 77 } },
        { name: 'Lucas Perrin', pos: 'CB', age: 24, rating: 75, attributes: { pace: 70, shooting: 44, passing: 70, dribbling: 70, defending: 76, physical: 78, overall: 75 } },
        { name: 'Frederic Guilbert', pos: 'RB', age: 28, rating: 77, attributes: { pace: 80, shooting: 66, passing: 75, dribbling: 76, defending: 75, physical: 78, overall: 77 } },
        { name: 'Marvin Senaya', pos: 'RB', age: 22, rating: 73, attributes: { pace: 82, shooting: 58, passing: 72, dribbling: 74, defending: 70, physical: 74, overall: 73 } },
        { name: 'Jean-Eudes Aholou', pos: 'CDM', age: 29, rating: 77, attributes: { pace: 70, shooting: 68, passing: 75, dribbling: 74, defending: 77, physical: 82, overall: 77 } },
        { name: 'Ibrahima Sissoko', pos: 'CM', age: 25, rating: 77, attributes: { pace: 74, shooting: 68, passing: 74, dribbling: 76, defending: 76, physical: 82, overall: 77 } },
        { name: 'Dion Moisés Pereira', pos: 'CM', age: 22, rating: 72, attributes: { pace: 74, shooting: 64, passing: 72, dribbling: 74, defending: 64, physical: 70, overall: 72 } },
        { name: 'Sanjin Prcić', pos: 'CM', age: 29, rating: 76, attributes: { pace: 70, shooting: 72, passing: 78, dribbling: 78, defending: 64, physical: 72, overall: 76 } },
        { name: 'Habib Diarra', pos: 'CM', age: 19, rating: 76, attributes: { pace: 80, shooting: 70, passing: 74, dribbling: 78, defending: 68, physical: 78, overall: 76 } },
        { name: 'Jean-Ricner Bellegarde', pos: 'RM', age: 25, rating: 79, attributes: { pace: 86, shooting: 73, passing: 76, dribbling: 82, defending: 58, physical: 74, overall: 79 } },
        { name: 'Kévin Gameiro', pos: 'ST', age: 36, rating: 78, attributes: { pace: 78, shooting: 79, passing: 72, dribbling: 78, defending: 44, physical: 68, overall: 78 } },
        { name: 'Lebo Mothiba', pos: 'ST', age: 27, rating: 77, attributes: { pace: 78, shooting: 78, passing: 66, dribbling: 74, defending: 38, physical: 82, overall: 77 } },
        { name: 'Habib Diallo', pos: 'ST', age: 28, rating: 81, attributes: { pace: 78, shooting: 83, passing: 72, dribbling: 76, defending: 42, physical: 82, overall: 81 } }
      ]
    },
    {
      code: 'sb29',
      name: 'Stade Brestois 29',
      shortName: 'Brest',
      balance: 185000,
      ticketsPrice: 17,
      sponsor: { name: 'Queguiner', monthly: 52000 },
      players: [
        { name: 'Marco Bizot', pos: 'GK', age: 32, rating: 79, attributes: { pace: 52, shooting: 20, passing: 72, dribbling: 68, defending: 18, physical: 75, overall: 79 } },
        { name: 'Joaquín Blázquez', pos: 'GK', age: 22, rating: 70, attributes: { pace: 48, shooting: 18, passing: 62, dribbling: 60, defending: 16, physical: 68, overall: 70 } },
        { name: 'Lilian Brassier', pos: 'CB', age: 23, rating: 77, attributes: { pace: 74, shooting: 48, passing: 72, dribbling: 70, defending: 78, physical: 80, overall: 77 } },
        { name: 'Brendan Chardonnet', pos: 'CB', age: 28, rating: 76, attributes: { pace: 70, shooting: 44, passing: 70, dribbling: 68, defending: 78, physical: 80, overall: 76 } },
        { name: 'Achraf Dari', pos: 'CB', age: 24, rating: 75, attributes: { pace: 72, shooting: 45, passing: 68, dribbling: 68, defending: 76, physical: 80, overall: 75 } },
        { name: 'Noah Fadiga', pos: 'RB', age: 23, rating: 74, attributes: { pace: 82, shooting: 58, passing: 72, dribbling: 76, defending: 70, physical: 74, overall: 74 } },
        { name: 'Bradley Locko', pos: 'LB', age: 21, rating: 75, attributes: { pace: 82, shooting: 58, passing: 72, dribbling: 76, defending: 72, physical: 76, overall: 75 } },
        { name: 'Hugo Magnetti', pos: 'CM', age: 25, rating: 75, attributes: { pace: 72, shooting: 64, passing: 74, dribbling: 74, defending: 74, physical: 78, overall: 75 } },
        { name: 'Mahdi Camara', pos: 'CM', age: 25, rating: 77, attributes: { pace: 76, shooting: 72, passing: 76, dribbling: 78, defending: 74, physical: 80, overall: 77 } },
        { name: 'Haris Belkebla', pos: 'CDM', age: 29, rating: 76, attributes: { pace: 72, shooting: 64, passing: 74, dribbling: 74, defending: 78, physical: 80, overall: 76 } },
        { name: 'Romain Del Castillo', pos: 'RW', age: 27, rating: 78, attributes: { pace: 82, shooting: 74, passing: 78, dribbling: 82, defending: 48, physical: 72, overall: 78 } },
        { name: 'Franck Honorat', pos: 'RW', age: 26, rating: 79, attributes: { pace: 90, shooting: 76, passing: 78, dribbling: 82, defending: 45, physical: 72, overall: 79 } },
        { name: 'Jérémy Le Douaron', pos: 'LW', age: 25, rating: 77, attributes: { pace: 80, shooting: 74, passing: 74, dribbling: 78, defending: 48, physical: 78, overall: 77 } },
        { name: 'Hugo Cuyper', pos: 'ST', age: 26, rating: 78, attributes: { pace: 78, shooting: 80, passing: 68, dribbling: 74, defending: 44, physical: 78, overall: 78 } },
        { name: 'Steve Mounié', pos: 'ST', age: 28, rating: 77, attributes: { pace: 71, shooting: 78, passing: 66, dribbling: 72, defending: 46, physical: 86, overall: 77 } },
        { name: 'Islam Slimani', pos: 'ST', age: 35, rating: 76, attributes: { pace: 66, shooting: 78, passing: 70, dribbling: 72, defending: 44, physical: 82, overall: 76 } },
        { name: 'Kamory Doumbia', pos: 'AM', age: 20, rating: 74, attributes: { pace: 80, shooting: 72, passing: 74, dribbling: 80, defending: 42, physical: 68, overall: 74 } }
      ]
    },
    {
      code: 'hacf',
      name: 'Le Havre AC',
      shortName: 'Le Havre',
      balance: 170000,
      ticketsPrice: 16,
      sponsor: { name: 'Sopalin', monthly: 48000 },
      players: [
        { name: 'Arthur Desmas', pos: 'GK', age: 30, rating: 74, attributes: { pace: 50, shooting: 18, passing: 66, dribbling: 62, defending: 18, physical: 72, overall: 74 } },
        { name: 'Mathieu Gorgelin', pos: 'GK', age: 32, rating: 72, attributes: { pace: 48, shooting: 18, passing: 64, dribbling: 60, defending: 18, physical: 70, overall: 72 } },
        { name: 'Christopher Operi', pos: 'LB', age: 26, rating: 73, attributes: { pace: 82, shooting: 58, passing: 72, dribbling: 74, defending: 70, physical: 76, overall: 73 } },
        { name: 'Gautier Lloris', pos: 'CB', age: 28, rating: 75, attributes: { pace: 70, shooting: 48, passing: 70, dribbling: 68, defending: 76, physical: 80, overall: 75 } },
        { name: 'Arouna Sangante', pos: 'CB', age: 21, rating: 76, attributes: { pace: 74, shooting: 46, passing: 70, dribbling: 70, defending: 78, physical: 82, overall: 76 } },
        { name: 'Yoann Salmier', pos: 'CB', age: 30, rating: 74, attributes: { pace: 70, shooting: 46, passing: 68, dribbling: 68, defending: 75, physical: 82, overall: 74 } },
        { name: 'Oualid El Hajjam', pos: 'RB', age: 32, rating: 74, attributes: { pace: 78, shooting: 54, passing: 72, dribbling: 74, defending: 74, physical: 76, overall: 74 } },
        { name: 'Nabil Alioui', pos: 'LW', age: 23, rating: 74, attributes: { pace: 84, shooting: 70, passing: 72, dribbling: 80, defending: 42, physical: 68, overall: 74 } },
        { name: 'Loïc Négo', pos: 'RM', age: 32, rating: 75, attributes: { pace: 84, shooting: 68, passing: 74, dribbling: 78, defending: 65, physical: 74, overall: 75 } },
        { name: 'Abdoulaye Touré', pos: 'CDM', age: 29, rating: 75, attributes: { pace: 70, shooting: 64, passing: 74, dribbling: 74, defending: 76, physical: 80, overall: 75 } },
        { name: 'Victor Lekhal', pos: 'CM', age: 29, rating: 75, attributes: { pace: 72, shooting: 66, passing: 76, dribbling: 76, defending: 74, physical: 78, overall: 75 } },
        { name: 'Yassine Kechta', pos: 'CM', age: 21, rating: 73, attributes: { pace: 74, shooting: 66, passing: 74, dribbling: 76, defending: 66, physical: 70, overall: 73 } },
        { name: 'Josué Casimir', pos: 'RW', age: 20, rating: 72, attributes: { pace: 86, shooting: 68, passing: 70, dribbling: 78, defending: 40, physical: 66, overall: 72 } },
        { name: 'Antoine Joujou', pos: 'AM', age: 20, rating: 71, attributes: { pace: 78, shooting: 66, passing: 72, dribbling: 76, defending: 42, physical: 68, overall: 71 } },
        { name: 'Jérémy Livolant', pos: 'RW', age: 25, rating: 74, attributes: { pace: 84, shooting: 70, passing: 72, dribbling: 78, defending: 44, physical: 70, overall: 74 } },
        { name: 'Mohamed Bayo', pos: 'ST', age: 25, rating: 77, attributes: { pace: 78, shooting: 77, passing: 66, dribbling: 75, defending: 40, physical: 82, overall: 77 } },
        { name: 'Jamal Thiaré', pos: 'ST', age: 29, rating: 74, attributes: { pace: 82, shooting: 74, passing: 66, dribbling: 74, defending: 42, physical: 78, overall: 74 } },
        { name: 'Nolan Mbemba', pos: 'CM', age: 27, rating: 73, attributes: { pace: 72, shooting: 64, passing: 72, dribbling: 74, defending: 66, physical: 72, overall: 73 } }
      ]
    },
    {
      code: 'fcmetz',
      name: 'FC Metz',
      shortName: 'Metz',
      balance: 165000,
      ticketsPrice: 16,
      sponsor: { name: 'Moselle Fibre', monthly: 47000 },
      players: [
        { name: 'Alexandre Oukidja', pos: 'GK', age: 34, rating: 77, attributes: { pace: 52, shooting: 20, passing: 70, dribbling: 66, defending: 18, physical: 74, overall: 77 } },
        { name: 'Marc-Aurèle Caillard', pos: 'GK', age: 29, rating: 73, attributes: { pace: 50, shooting: 18, passing: 66, dribbling: 64, defending: 16, physical: 72, overall: 73 } },
        { name: 'Ismaël Traoré', pos: 'CB', age: 37, rating: 75, attributes: { pace: 60, shooting: 50, passing: 68, dribbling: 66, defending: 78, physical: 80, overall: 75 } },
        { name: 'Fali Candé', pos: 'CB', age: 25, rating: 76, attributes: { pace: 74, shooting: 52, passing: 70, dribbling: 70, defending: 78, physical: 82, overall: 76 } },
        { name: 'Matthieu Udol', pos: 'LB', age: 27, rating: 77, attributes: { pace: 80, shooting: 60, passing: 74, dribbling: 76, defending: 74, physical: 78, overall: 77 } },
        { name: 'Koffi Kouao', pos: 'RB', age: 24, rating: 76, attributes: { pace: 84, shooting: 58, passing: 72, dribbling: 76, defending: 74, physical: 78, overall: 76 } },
        { name: 'Lamine Camara', pos: 'CM', age: 19, rating: 74, attributes: { pace: 76, shooting: 66, passing: 74, dribbling: 76, defending: 70, physical: 74, overall: 74 } },
        { name: 'Habib Maïga', pos: 'CM', age: 27, rating: 76, attributes: { pace: 74, shooting: 70, passing: 74, dribbling: 74, defending: 74, physical: 80, overall: 76 } },
        { name: 'Kévin N’Doram', pos: 'CDM', age: 27, rating: 75, attributes: { pace: 72, shooting: 60, passing: 72, dribbling: 72, defending: 76, physical: 78, overall: 75 } },
        { name: 'Lamine Gueye', pos: 'LW', age: 24, rating: 75, attributes: { pace: 88, shooting: 68, passing: 72, dribbling: 80, defending: 40, physical: 70, overall: 75 } },
        { name: 'Pape Ndiaga Yade', pos: 'RW', age: 23, rating: 74, attributes: { pace: 86, shooting: 70, passing: 72, dribbling: 80, defending: 40, physical: 70, overall: 74 } },
        { name: 'Ablie Jallow', pos: 'RW', age: 24, rating: 75, attributes: { pace: 91, shooting: 70, passing: 72, dribbling: 82, defending: 42, physical: 68, overall: 75 } },
        { name: 'Georges Mikautadze', pos: 'ST', age: 22, rating: 79, attributes: { pace: 82, shooting: 81, passing: 72, dribbling: 80, defending: 42, physical: 72, overall: 79 } },
        { name: 'Mikaël Biron', pos: 'ST', age: 25, rating: 74, attributes: { pace: 78, shooting: 76, passing: 64, dribbling: 74, defending: 40, physical: 74, overall: 74 } },
        { name: 'Didier Lamkel Zé', pos: 'LW', age: 26, rating: 74, attributes: { pace: 82, shooting: 72, passing: 70, dribbling: 78, defending: 38, physical: 80, overall: 74 } },
        { name: 'Cheikh Sabaly', pos: 'RW', age: 24, rating: 73, attributes: { pace: 84, shooting: 70, passing: 68, dribbling: 76, defending: 38, physical: 70, overall: 73 } },
        { name: 'Joel Asoro', pos: 'ST', age: 24, rating: 74, attributes: { pace: 86, shooting: 74, passing: 66, dribbling: 76, defending: 40, physical: 72, overall: 74 } },
        { name: 'Ibou Sané', pos: 'CM', age: 22, rating: 72, attributes: { pace: 72, shooting: 64, passing: 72, dribbling: 74, defending: 64, physical: 70, overall: 72 } }
      ]
    },
    {
      code: 'cf63',
      name: 'Clermont Foot 63',
      shortName: 'Clermont',
      balance: 175000,
      ticketsPrice: 16,
      sponsor: { name: 'Michelin', monthly: 50000 },
      players: [
        { name: 'Mory Diaw', pos: 'GK', age: 30, rating: 77, attributes: { pace: 52, shooting: 20, passing: 70, dribbling: 66, defending: 18, physical: 74, overall: 77 } },
        { name: 'Mehdi Zeffane', pos: 'RB', age: 31, rating: 74, attributes: { pace: 80, shooting: 58, passing: 72, dribbling: 74, defending: 72, physical: 76, overall: 74 } },
        { name: 'Akim Zedadka', pos: 'RB', age: 28, rating: 75, attributes: { pace: 83, shooting: 60, passing: 73, dribbling: 76, defending: 72, physical: 78, overall: 75 } },
        { name: 'Maximiliano Caufriez', pos: 'CB', age: 26, rating: 76, attributes: { pace: 72, shooting: 46, passing: 70, dribbling: 68, defending: 78, physical: 82, overall: 76 } },
        { name: 'Mateusz Wieteska', pos: 'CB', age: 26, rating: 76, attributes: { pace: 70, shooting: 48, passing: 70, dribbling: 68, defending: 78, physical: 82, overall: 76 } },
        { name: 'Alidu Seidu', pos: 'CB', age: 22, rating: 76, attributes: { pace: 74, shooting: 45, passing: 70, dribbling: 70, defending: 78, physical: 82, overall: 76 } },
        { name: 'Neto Borges', pos: 'LB', age: 26, rating: 76, attributes: { pace: 82, shooting: 60, passing: 74, dribbling: 76, defending: 74, physical: 80, overall: 76 } },
        { name: 'Johan Gastien', pos: 'CDM', age: 35, rating: 75, attributes: { pace: 64, shooting: 68, passing: 78, dribbling: 76, defending: 72, physical: 70, overall: 75 } },
        { name: 'Muhammed Cham', pos: 'AM', age: 23, rating: 78, attributes: { pace: 80, shooting: 76, passing: 78, dribbling: 82, defending: 48, physical: 72, overall: 78 } },
        { name: 'Saif-Eddine Khaoui', pos: 'CM', age: 28, rating: 77, attributes: { pace: 78, shooting: 74, passing: 78, dribbling: 80, defending: 58, physical: 70, overall: 77 } },
        { name: 'Maxime Gonalons', pos: 'CDM', age: 34, rating: 76, attributes: { pace: 62, shooting: 68, passing: 76, dribbling: 74, defending: 78, physical: 78, overall: 76 } },
        { name: 'Elbasan Rashani', pos: 'LW', age: 30, rating: 77, attributes: { pace: 80, shooting: 76, passing: 76, dribbling: 78, defending: 50, physical: 74, overall: 77 } },
        { name: 'Jim Allevinah', pos: 'RW', age: 28, rating: 76, attributes: { pace: 86, shooting: 74, passing: 74, dribbling: 80, defending: 45, physical: 72, overall: 76 } },
        { name: 'Grejohn Kyei', pos: 'ST', age: 28, rating: 77, attributes: { pace: 80, shooting: 78, passing: 70, dribbling: 76, defending: 42, physical: 80, overall: 77 } },
        { name: 'Komnen Andrić', pos: 'ST', age: 27, rating: 76, attributes: { pace: 78, shooting: 77, passing: 66, dribbling: 74, defending: 40, physical: 78, overall: 76 } },
        { name: 'Florent Ogier', pos: 'CB', age: 33, rating: 74, attributes: { pace: 62, shooting: 48, passing: 68, dribbling: 66, defending: 76, physical: 78, overall: 74 } },
        { name: 'Yoël Armougom', pos: 'LB', age: 25, rating: 74, attributes: { pace: 80, shooting: 60, passing: 72, dribbling: 74, defending: 72, physical: 76, overall: 74 } },
        { name: 'Ouparine Djoco', pos: 'GK', age: 24, rating: 74, attributes: { pace: 48, shooting: 22, passing: 68, dribbling: 62, defending: 20, physical: 72, overall: 74 } }
      ]
    }
  ]
};
